create external table cdmdwm.dwm_pmd_robot_asset_s_d (
    -- robot
    robot__robot_id string comment '机器人id标识，既是robot_code',
    robot__robot_name string comment '机器人名称',
    robot__robot_type_id string comment '机器人类型',
    robot__robot_type_inner_name string comment '机器人类型名(研发)',
    robot__robot_type_name string comment '机器人类型名',
    robot__asset_code string comment '资产code',
    robot__asset_type string comment '资产类型 001 达闼固资 002 达闼存货 003 客户资产,默认001',
    robot__asset_type_name string comment '资产类型名称 001 达闼固资 002 达闼存货 003 客户资产,默认001',
    robot__product_type_code string comment '产品类型code',
    robot__product_type_code_name string comment '产品类型code所对应的名称',
    robot__product_id string comment '产品ID',
    robot__product_id_name string comment '产品名字',
    robot__asset_status int comment '资产状态 1 在册 2 待测 3 研发测试 4 空闲 5 项目中',
    robot__asset_status_name string comment '资产状态名称 1 在册 2 待测 3 研发测试 4 空闲 5 项目中',
    robot__status int comment '机器人状态 robot状态: 1-正常 9-删除',
    robot__status_name string comment '机器人状态 robot状态: 1-正常 9-删除',
    robot__robot_manufacturer_id string comment '机器人制造商id',
    robot__robot_manufacturer_name string comment '机器人制造商名称',
    robot__model string comment 'robot型号,roc中model boss中device_model',
    robot__software_version string comment '机器人软件版本',
    robot__hardware_version string comment '机器人硬件版本',
    robot__sku string comment '机器人SKU',
    robot__quality_date string comment '供应商质保期',
    robot__customer_quality_date string comment '客户质保期',
    robot__product_date string comment '生产日期',
    robot__roc_delivery_status int comment 'ROC交付状态 0 已交付 1 未交付 2 交付中 3 回收中,默认为1',
    robot__roc_delivery_status_name string comment 'ROC交付状态名称 0 已交付 1 未交付 2 交付中 3 回收中,默认为1',
    robot__is_special_asset int comment '1常规资产 0特殊资产,默认1',
    robot__serial_number string comment '机器人序列号',
    robot__operating_status int comment '运营状态 1 空闲 2 测试中 3 演示中 4 运营中 5 交付中,默认1',
    robot__operating_status_name string comment '运营状态名称 1 空闲 2 测试中 3 演示中 4 运营中 5 交付中,默认1',
    robot__running_status int comment '运行状态 1 良好 2 故障 3 维修中,默认1',
    robot__running_status_name string comment '运行状态名称 1 良好 2 故障 3 维修中,默认1',
    robot__environment string comment '机器人属于哪个环境',
    robot__start_time string comment '当前机器人记录生效时间',
    robot__end_time string comment '当前机器人记录失效时间',
    robot__k8s_env_name string comment '环境名称',
    robot__create_time string comment '机器人信息创建时间',
    robot__update_time string comment '机器人信息更新时间',

    -- customer
    customer__customer_id string comment '客户id',
    customer__customer_name string comment '客户名称',
    customer__pid string comment '客户父级',
    customer__level string comment '当前客户层级',
    customer__region string comment '客户所在区域',
    customer__address string comment '客户地址',
    customer__website string comment '客户网址',
    customer__industry_id string comment '客户所属行业编码',
    customer__industry_name string comment '客户所属行业编码',
    customer__nature_code string comment '客户性质编码',
    customer__nature_name string comment '客户性质名称',
    customer__credit_code string comment '客户信用编码',
    customer__credit_name string comment '客户信用名称',
    customer__source_code string comment '客户来源编码',
    customer__source_name string comment '客户来源名称',
    customer__scale_code string comment '公司规模编码',
    customer__scale_name string comment '公司规模名称',
    customer__status_code string comment '客户行业地位编码',
    customer__status_name string comment '客户行业地位名称',
    customer__contact_code string comment '联系策略编码',
    customer__contact_name string comment '联系策略名称',
    customer__purchase_code string comment '客户购买策略编码',
    customer__purchase_name string comment '客户购买策略名称',
    customer__employment_code string comment '客户从业时间编号',
    customer__employment_name string comment '客户从业时间名称',
    customer__settlement_code string comment '结算方式编码',
    customer__settlement_name string comment '结算方式名称',
    customer__employer_num int comment '客户员工数量',

    -- tenant
    tenant__tenant_id string comment '租户code码',
    tenant__tenant_name	string comment '租户名称',
    tenant__tenant_type	int comment '租户类型',
    tenant__tenant_type_name string comment '租户类型名称: 0长租、1短租、2试用、3售卖、4测试',
    tenant__vop_id string comment '关联的虚拟运营商id',
    tenant__industry_id	string comment '租户所属行业id',
    tenant__industry_name	string comment '租户所属行业名称',
    tenant__sub_sys	string comment '子系统',
    tenant__time_zone string comment '时区',
    tenant__net_env_id string comment '网络环境',
    tenant__mcs_area string	comment 'vpn区域代码',
    tenant__device_num int comment 'vpn限制设备数',
    tenant__region string comment '地区',
    tenant__country string COMMENT '国家',
    tenant__province string COMMENT '省份',
    tenant__city string COMMENT '城市',
    tenant__address	string comment '地址',
    tenant__contact	string comment '租户联系人',
    tenant__phone string comment '联系电话',
    tenant__phone_area_code string COMMENT '手机区域编码',
    tenant__telephone string comment '联系电话',
    tenant__project_name string COMMENT '项目名称',
    tenant__district string comment '所属区域地图',
    tenant__seller string comment '销售人员',
    tenant__email string comment '邮箱地址',
    tenant__boss_status int comment '租户状态: 1-有效 9-删除',
    tenant__boss_status_name string comment '租户状态',
    tenant__roc_status int comment '租户roc状态: -1-删除;0-正常;1-待开通;2-锁定',
    tenant__roc_status_name string comment '租户roc状态',
    tenant__charge_time	string comment '计费开始时间',
    tenant__expired_time string	comment '租户过期时间',
    tenant__logo string	comment '租户logo地址',
    tenant__description	string	comment '租户简要描述',
    tenant__brand string comment '客户品牌化参数',
    tenant__is_need_vpn	int comment '是否需要VPN: 0-不需要;1-需要',
    tenant__service_address string COMMENT '服务地址',
    tenant__create_time	string comment '租户创建时间',

    -- asset_record
    asset_record_id string COMMENT 'id',
    asset_record__action_type int COMMENT '操作类型 1 交付 2 内部领用 3 报障 4 维修 5 回库 6 入库 7 调拨 ',
    asset_record__action_type_name string COMMENT '操作类型 1 交付 2 内部领用 3 报障 4 维修 5 回库 6 入库 7 调拨 ',
    order_id string COMMENT '订单编码',
    ext_data string COMMENT '扩展信息',
    asset_record__record_start_time string COMMENT '开始时间',
    asset_record__record_end_time string COMMENT '结束时间',
    asset_record__status int COMMENT '状态 1 空闲 2 测试中 3 演示中 4 运营中 5 交付中 6 待回收 7 正常 8 停用 9 故障 10 维修中',
    asset_record__status_name string COMMENT '状态 1 空闲 2 测试中 3 演示中 4 运营中 5 交付中 6 待回收 7 正常 8 停用 9 故障 10 维修中',
    asset_record__cause_type int COMMENT '故障原因 1 达闼原因 2 客户原因',
    asset_record__cause_type_name string COMMENT '故障原因 1 达闼原因 2 客户原因',
    staff_id string COMMENT '操作人员ID',
    staff_name string COMMENT '操作员名字',
    event_time string comment '事件发生时间,选的update_time作为事件时间',
    asset_record__k8s_env_name string  comment '环境名称',
    asset_record__create_time string COMMENT '创建时间',
    asset_record__update_time string COMMENT '更新时间'
)
comment '机器人资源记录表'
partitioned by(dt string comment 'dt分区字段')
stored as parquet
location '/data/cdmdwm/dwm_pmd_robot_asset_s_d';