set hive.exec.dynamic.partition.mode = nonstrict;
set hive.merge.mapfiles = true;
set hive.merge.mapredfiles = true;
set hive.exec.max.dynamic.partitions = 60000;
set mapreduce.job.queuename=root.users.liuhao;

with robot_snapshot as (
    select
        robot_id as robot__robot_id,
        robot_name as robot__robot_name,
        robot_type_id as robot__robot_type_id,
        robot_type_inner_name as robot__robot_type_inner_name,
        robot_type_name as robot__robot_type_name,
        tenant_id as robot__tenant_id,
        asset_code as robot__asset_code,
        asset_type as robot__asset_type,
        asset_type_name as robot__asset_type_name,
        product_type_code as robot__product_type_code,
        product_type_code_name as robot__product_type_code_name,
        product_id as robot__product_id,
        product_id_name as robot__product_id_name,
        asset_status as robot__asset_status,
        asset_status_name as robot__asset_status_name,
        status as robot__status,
        status_name as robot__status_name,
        robot_manufacturer_id as robot__robot_manufacturer_id,
        robot_manufacturer_name as robot__robot_manufacturer_name,
        model as robot__model,
        software_version as robot__software_version,
        hardware_version as robot__hardware_version,
        sku as robot__sku,
        quality_date as robot__quality_date,
        customer_quality_date as robot__customer_quality_date,
        product_date as robot__product_date,
        roc_delivery_status as robot__roc_delivery_status,
        roc_delivery_status_name as robot__roc_delivery_status_name,
        is_special_asset as robot__is_special_asset,
        serial_number as robot__serial_number,
        operating_status as robot__operating_status,
        operating_status_name as robot__operating_status_name,
        running_status as robot__running_status,
        running_status_name as robot__running_status_name,
        environment as robot__environment,
        start_time as robot__start_time,
        end_time as robot__end_time,
        k8s_env_name as robot__k8s_env_name,
        create_time as robot__create_time,
        update_time as robot__update_time
--     from cdmdim.dim_pmd_robot_sh_d
    from cdmtmp.tmp_dim_pmd_robot_sh_d_luojun_20220130
    where dt = date_sub(current_date,1) and (tenant_id != '' or roc_delivery_status != 3) and end_time = '9999-12-31 23:59:59.999'
),
robot_info as (
    select
        p1.robot__robot_id,
        p1.robot__robot_name,
        p1.robot__robot_type_id,
        p1.robot__robot_type_inner_name,
        p1.robot__robot_type_name,
        p1.robot__tenant_id,
        p1.robot__asset_code,
        p1.robot__asset_type,
        p1.robot__asset_type_name,
        p1.robot__product_type_code,
        p1.robot__product_type_code_name,
        p1.robot__product_id,
        p1.robot__product_id_name,
        p1.robot__asset_status,
        p1.robot__asset_status_name,
        p1.robot__status,
        p1.robot__status_name,
        p1.robot__robot_manufacturer_id,
        p1.robot__robot_manufacturer_name,
        p1.robot__model,
        p1.robot__software_version,
        p1.robot__hardware_version,
        p1.robot__sku,
        p1.robot__quality_date,
        p1.robot__customer_quality_date,
        p1.robot__product_date,
        p1.robot__roc_delivery_status,
        p1.robot__roc_delivery_status_name,
        p1.robot__is_special_asset,
        p1.robot__serial_number,
        p1.robot__operating_status,
        p1.robot__operating_status_name,
        p1.robot__running_status,
        p1.robot__running_status_name,
        p1.robot__environment,
        p1.robot__start_time,
        p1.robot__end_time,
        p1.robot__k8s_env_name,
        p1.robot__create_time,
        p1.robot__update_time,

        case when p1.customer_id != '' then p1.customer_id
             else nvl(p2.customer_id,'')
        end as customer__customer_id,
        nvl(p2.customer_name,'') as customer__customer_name,
        nvl(p2.pid,'') as customer__pid,
        nvl(p2.level,-99999998) as customer__level,
        nvl(p2.region,'') as customer__region,
        nvl(p2.address,'') as customer__address,
        nvl(p2.website,'') as customer__website,
        nvl(p2.industry_id,'') as customer__industry_id,
        nvl(p2.nature_code,'') as customer__nature_code,
        nvl(p2.nature_name,'') as customer__nature_name,
        nvl(p2.credit_code,'') as customer__credit_code,
        nvl(p2.credit_name,'') as customer__credit_name,
        nvl(p2.source_code,'') as customer__source_code,
        nvl(p2.source_name,'') as customer__source_name,
        nvl(p2.scale_code,'') as customer__scale_code,
        nvl(p2.scale_name,'') as customer__scale_name,
        nvl(p2.status_code,'') as customer__status_code,
        nvl(p2.status_name,'') as customer__status_name,
        nvl(p2.contact_code,'') as customer__contact_code,
        nvl(p2.contact_name,'') as customer__contact_name,
        nvl(p2.purchase_code,'') as customer__purchase_code,
        nvl(p2.purchase_name,'') as customer__purchase_name,
        nvl(p2.employment_code,'') as customer__employment_code,
        nvl(p2.employment_name,'') as customer__employment_name,
        nvl(p2.settlement_code,'') as customer__settlement_code,
        nvl(p2.settlement_name,'') as customer__settlement_name,
        nvl(p2.employer_num,-99999998) as customer__employer_num,

        p1.tenant__tenant_id,
        p1.tenant__tenant_name,
        p1.tenant__tenant_type,
        p1.tenant__tenant_type_name,
        p1.tenant__vop_id,
        p1.tenant__industry_id,
        p1.tenant__sub_sys,
        p1.tenant__time_zone,
        p1.tenant__net_env_id,
        p1.tenant__mcs_area,
        p1.tenant__device_num,
        p1.tenant__region,
        p1.tenant__country,
        p1.tenant__province,
        p1.tenant__city,
        p1.tenant__address,
        p1.tenant__contact,
        p1.tenant__phone,
        p1.tenant__phone_area_code,
        p1.tenant__telephone,
        p1.tenant__project_name,
        p1.tenant__district,
        p1.tenant__seller,
        p1.tenant__email,
        p1.tenant__boss_status,
        p1.tenant__boss_status_name,
        p1.tenant__roc_status,
        p1.tenant__roc_status_name,
        p1.tenant__charge_time,
        p1.tenant__expired_time,
        p1.tenant__logo,
        p1.tenant__description,
        p1.tenant__brand,
        p1.tenant__is_need_vpn,
        p1.tenant__service_address,
        p1.tenant__create_time,

        p1.asset_record_id,
        p1.action_type as asset_record__action_type,
        p1.action_type_name as asset_record__action_type_name,
        p1.order_id,
        p1.ext_data,
        p1.record_start_time as asset_record__record_start_time,
        p1.record_end_time as asset_record__record_end_time,
        p1.status as asset_record__status,
        p1.status_name as asset_record__status_name,
        p1.cause_type as asset_record__cause_type,
        p1.cause_type_name as asset_record__cause_type_name,
        p1.staff_id,
        p1.staff_name,
        p1.event_time,
        p1.asset_record__k8s_env_name,
        p1.asset_record__create_time,
        p1.asset_record__update_time
    from (
        select
            x1.robot__robot_id,
            x1.robot__robot_name,
            x1.robot__robot_type_id,
            x1.robot__robot_type_inner_name,
            x1.robot__robot_type_name,
            x1.robot__tenant_id,
            x1.robot__asset_code,
            x1.robot__asset_type,
            x1.robot__asset_type_name,
            x1.robot__product_type_code,
            x1.robot__product_type_code_name,
            x1.robot__product_id,
            x1.robot__product_id_name,
            x1.robot__asset_status,
            x1.robot__asset_status_name,
            x1.robot__status,
            x1.robot__status_name,
            x1.robot__robot_manufacturer_id,
            x1.robot__robot_manufacturer_name,
            x1.robot__model,
            x1.robot__software_version,
            x1.robot__hardware_version,
            x1.robot__sku,
            x1.robot__quality_date,
            x1.robot__customer_quality_date,
            x1.robot__product_date,
            x1.robot__roc_delivery_status,
            x1.robot__roc_delivery_status_name,
            x1.robot__is_special_asset,
            x1.robot__serial_number,
            x1.robot__operating_status,
            x1.robot__operating_status_name,
            x1.robot__running_status,
            x1.robot__running_status_name,
            x1.robot__environment,
            x1.robot__start_time,
            x1.robot__end_time,
            x1.robot__k8s_env_name,
            x1.robot__create_time,
            x1.robot__update_time,

            nvl(x2.tenant_id,'') as tenant__tenant_id,
            nvl(x2.tenant_name,'') as tenant__tenant_name,
            nvl(x2.tenant_type,-99999998) as tenant__tenant_type,
            nvl(x2.tenant_type_name,'未知') as tenant__tenant_type_name,
            nvl(x2.vop_id,'') as tenant__vop_id,
            nvl(x2.customer_id,'') as tenant__customer_id,
            nvl(x2.industry_id,'') as tenant__industry_id,
            nvl(x2.sub_sys,'') as tenant__sub_sys,
            nvl(x2.time_zone,'') as tenant__time_zone,
            nvl(x2.net_env_id,'') as tenant__net_env_id,
            nvl(x2.mcs_area,'') as tenant__mcs_area,
            nvl(x2.device_num,-99999998) as tenant__device_num,
            nvl(x2.region,'') as tenant__region,
            nvl(x2.country,'') as tenant__country,
            nvl(x2.province,'') as tenant__province,
            nvl(x2.city,'') as tenant__city,
            nvl(x2.address,'') as tenant__address,
            nvl(x2.contact,'') as tenant__contact,
            nvl(x2.phone,'') as tenant__phone,
            nvl(x2.phone_area_code,'') as tenant__phone_area_code,
            nvl(x2.telephone,'') as tenant__telephone,
            nvl(x2.project_name,'') as tenant__project_name,
            nvl(x2.district,'') as tenant__district,
            nvl(x2.seller,'') as tenant__seller,
            nvl(x2.email,'') as tenant__email,
            nvl(x2.boss_status,-99999998) as tenant__boss_status,
            nvl(x2.boss_status_name,'未知') as tenant__boss_status_name,
            nvl(x2.roc_status,-99999998) as tenant__roc_status,
            nvl(x2.roc_status_name,'未知') as tenant__roc_status_name,
            nvl(x2.charge_time,'') as tenant__charge_time,
            nvl(x2.expired_time,'') as tenant__expired_time,
            nvl(x2.logo,'') as tenant__logo,
            nvl(x2.description,'') as tenant__description,
            nvl(x2.brand,'') as tenant__brand,
            nvl(x2.is_need_vpn,-99999998) as tenant__is_need_vpn,
            nvl(x2.service_address,'') as tenant__service_address,
            nvl(x2.create_time,'') as tenant__create_time,
            nvl(x2.update_time,'') as tenant__update_time,
            nvl(x2.start_time,'') as tenant__start_time,
            nvl(x2.end_time,'') as tenant__end_time,
            nvl(x2.k8s_env_name,'') as tenant__k8s_env_name,

            case when x1.customer_id != '' then x1.customer_id
                 else nvl(x2.customer_id,'')
            end as customer_id,
            nvl(x1.asset_record_id,'') as asset_record_id,
            x1.action_type,
            x1.action_type_name,
            x1.order_id,
            x1.ext_data,
            x1.record_start_time,
            x1.record_end_time,
            x1.status,
            x1.status_name,
            x1.cause_type,
            x1.cause_type_name,
            x1.staff_id,
            x1.staff_name,
            x1.event_time,
            x1.asset_record__k8s_env_name,
            x1.asset_record__create_time,
            x1.asset_record__update_time
        from (
           select
               t1.robot__robot_id,
               t1.robot__robot_name,
               t1.robot__robot_type_id,
               t1.robot__robot_type_inner_name,
               t1.robot__robot_type_name,
               case when t1.robot__tenant_id != '' then t1.robot__tenant_id
                    else nvl(t1.robot__tenant_id,'')
               end as robot__tenant_id,
               case when t1.robot__asset_code != '' then t1.robot__asset_code
                    else nvl(t1.robot__asset_code,'')
               end as robot__asset_code,
               t1.robot__asset_type,
               t1.robot__asset_type_name,
               t1.robot__product_type_code,
               t1.robot__product_type_code_name,
               t1.robot__product_id,
               t1.robot__product_id_name,
               t1.robot__asset_status,
               t1.robot__asset_status_name,
               t1.robot__status,
               t1.robot__status_name,
               t1.robot__robot_manufacturer_id,
               t1.robot__robot_manufacturer_name,
               t1.robot__model,
               t1.robot__software_version,
               t1.robot__hardware_version,
               t1.robot__sku,
               t1.robot__quality_date,
               t1.robot__customer_quality_date,
               t1.robot__product_date,
               t1.robot__roc_delivery_status,
               t1.robot__roc_delivery_status_name,
               t1.robot__is_special_asset,
               t1.robot__serial_number,
               t1.robot__operating_status,
               t1.robot__operating_status_name,
               t1.robot__running_status,
               t1.robot__running_status_name,
               t1.robot__environment,
               t1.robot__start_time,
               t1.robot__end_time,
               t1.robot__k8s_env_name,
               t1.robot__create_time,
               t1.robot__update_time,
               nvl(t2.asset_record_id,'') as asset_record_id,
               nvl(t2.action_type,-99999998) as action_type,
               nvl(t2.action_type_name,'未知') as action_type_name,
               nvl(t2.customer_id,'') as customer_id,
               nvl(t2.order_id,'') as order_id,
               nvl(t2.ext_data,'') as ext_data,
               nvl(t2.record_start_time,'') as record_start_time,
               nvl(t2.record_end_time,'') as record_end_time,
               nvl(t2.status,-99999998) as status,
               nvl(t2.status_name,'未知') as status_name,
               nvl(t2.cause_type,-99999998) as cause_type,
               nvl(t2.cause_type_name,'未知') as cause_type_name,
               nvl(t2.staff_id,'') as staff_id,
               nvl(t2.staff_name,'') as staff_name,
               nvl(t2.event_time,'') as event_time,
               nvl(t2.k8s_env_name,'') as asset_record__k8s_env_name,
               nvl(t2.create_time,'') as asset_record__create_time,
               nvl(t2.update_time,'') as asset_record__update_time
           from robot_snapshot t1
           left join (
                select
                    asset_record_id,
                    asset_code,
                    robot_id,
                    action_type,
                    action_type_name,
                    tenant_id,
                    customer_id,
                    order_id,
                    ext_data,
                    record_start_time,
                    record_end_time,
                    status,
                    status_name,
                    cause_type,
                    cause_type_name,
                    staff_id,
                    staff_name,
                    event_time,
                    k8s_env_name,
                    create_time,
                    update_time
                from (
                     select
                         asset_record_id,
                         asset_code,
                         robot_id,
                         action_type,
                         action_type_name,
                         tenant_id,
                         customer_id,
                         order_id,
                         ext_data,
                         record_start_time,
                         record_end_time,
                         status,
                         status_name,
                         cause_type,
                         cause_type_name,
                         staff_id,
                         staff_name,
                         event_time,
                         k8s_env_name,
                         create_time,
                         update_time,
                         row_number() OVER (PARTITION BY asset_record_id ORDER BY update_time DESC) as rnk
                     from cdmdwd.dwd_crio_pmd_asset_record_a_d
                ) q1 where q1.rnk = 1
           ) t2 on t1.robot__robot_id = t2.robot_id
        ) x1
       left join (
           select
               tenant_id,
               tenant_name,
               tenant_type,
               tenant_type_name,
               vop_id,
               customer_id,
               industry_id,
               sub_sys,
               time_zone,
               net_env_id,
               mcs_area,
               device_num,
               region,
               country,
               province,
               city,
               address,
               contact,
               phone,
               phone_area_code,
               telephone,
               project_name,
               district,
               seller,
               email,
               boss_status,
               boss_status_name,
               roc_status,
               roc_status_name,
               charge_time,
               expired_time,
               logo,
               description,
               brand,
               is_need_vpn,
               service_address,
               create_time,
               update_time,
               start_time,
               end_time,
               k8s_env_name
           from cdmdim.dim_umd_tenant_sh_d
           where dt = date_sub(current_date,1) and end_time = '9999-12-31 23:59:59.999'
        ) x2 on x1.robot__tenant_id = x2.tenant_id
    ) p1
    left join (
        select
            customer_id,
            customer_name,
            pid,
            level,
            region,
            address,
            website,
            industry_id,
            nature_code,
            nature_name,
            credit_code,
            credit_name,
            source_code,
            source_name,
            scale_code,
            scale_name,
            status_code,
            status_name,
            contact_code,
            contact_name,
            purchase_code,
            purchase_name,
            employment_code,
            employment_name,
            settlement_code,
            settlement_name,
            employer_num,
            category_code,
            category_name,
            create_time,
            update_time,
            start_time,
            end_time
        from cdmdim.dim_umd_customer_sh_d
        where dt = date_sub(current_date,1) and end_time = '9999-12-31 23:59:59.999'
    ) p2 on p1.customer_id = p2.customer_id
),
dim_add_industry as (
    select
        robot__robot_id,
        robot__robot_name,
        robot__robot_type_id,
        robot__robot_type_inner_name,
        robot__robot_type_name,
        robot__tenant_id,
        robot__asset_code,
        robot__asset_type,
        robot__asset_type_name,
        robot__product_type_code,
        robot__product_type_code_name,
        robot__product_id,
        robot__product_id_name,
        robot__asset_status,
        robot__asset_status_name,
        robot__status,
        robot__status_name,
        robot__robot_manufacturer_id,
        robot__robot_manufacturer_name,
        robot__model,
        robot__software_version,
        robot__hardware_version,
        robot__sku,
        robot__quality_date,
        robot__customer_quality_date,
        robot__product_date,
        robot__roc_delivery_status,
        robot__roc_delivery_status_name,
        robot__is_special_asset,
        robot__serial_number,
        robot__operating_status,
        robot__operating_status_name,
        robot__running_status,
        robot__running_status_name,
        robot__environment,
        robot__start_time,
        robot__end_time,
        robot__k8s_env_name,
        robot__create_time,
        robot__update_time,

        customer__customer_id,
        customer__customer_name,
        customer__pid,
        customer__level,
        customer__region,
        customer__address,
        customer__website,
        customer__industry_id,
        nvl(t3.industry_name,'') as customer__industry_name,
        customer__nature_code,
        customer__nature_name,
        customer__credit_code,
        customer__credit_name,
        customer__source_code,
        customer__source_name,
        customer__scale_code,
        customer__scale_name,
        customer__status_code,
        customer__status_name,
        customer__contact_code,
        customer__contact_name,
        customer__purchase_code,
        customer__purchase_name,
        customer__employment_code,
        customer__employment_name,
        customer__settlement_code,
        customer__settlement_name,
        customer__employer_num,

        tenant__tenant_id,
        tenant__tenant_name,
        tenant__tenant_type,
        tenant__tenant_type_name,
        tenant__vop_id,
        tenant__industry_id,
        nvl(t2.industry_name,'') as tenant__industry_name,
        tenant__sub_sys,
        tenant__time_zone,
        tenant__net_env_id,
        tenant__mcs_area,
        tenant__device_num,
        tenant__region,
        tenant__country,
        tenant__province,
        tenant__city,
        tenant__address,
        tenant__contact,
        tenant__phone,
        tenant__phone_area_code,
        tenant__telephone,
        tenant__project_name,
        tenant__district,
        tenant__seller,
        tenant__email,
        tenant__boss_status,
        tenant__boss_status_name,
        tenant__roc_status,
        tenant__roc_status_name,
        tenant__charge_time,
        tenant__expired_time,
        tenant__logo,
        tenant__description,
        tenant__brand,
        tenant__is_need_vpn,
        tenant__service_address,
        tenant__create_time,

        asset_record_id,
        asset_record__action_type,
        asset_record__action_type_name,
        order_id,
        ext_data,
        asset_record__record_start_time,
        asset_record__record_end_time,
        asset_record__status,
        asset_record__status_name,
        asset_record__cause_type,
        asset_record__cause_type_name,
        staff_id,
        staff_name,
        event_time,
        asset_record__k8s_env_name,
        asset_record__create_time,
        asset_record__update_time,
        row_number() OVER (PARTITION BY robot__robot_id ORDER BY asset_record__update_time DESC) as rnk
    from robot_info t1
    left join cdmdim.dim_umd_industry_a_d t2 on t1.tenant__industry_id = t2.industry_id
    left join cdmdim.dim_umd_industry_a_d t3 on t1.customer__industry_id = t3.industry_id
),
remove_duplict as (
    select
        robot__robot_id,
        robot__robot_name,
        robot__robot_type_id,
        robot__robot_type_inner_name,
        robot__robot_type_name,
        robot__tenant_id,
        robot__asset_code,
        robot__asset_type,
        robot__asset_type_name,
        robot__product_type_code,
        robot__product_type_code_name,
        robot__product_id,
        robot__product_id_name,
        robot__asset_status,
        robot__asset_status_name,
        robot__status,
        robot__status_name,
        robot__robot_manufacturer_id,
        robot__robot_manufacturer_name,
        robot__model,
        robot__software_version,
        robot__hardware_version,
        robot__sku,
        robot__quality_date,
        robot__customer_quality_date,
        robot__product_date,
        robot__roc_delivery_status,
        robot__roc_delivery_status_name,
        robot__is_special_asset,
        robot__serial_number,
        robot__operating_status,
        robot__operating_status_name,
        robot__running_status,
        robot__running_status_name,
        robot__environment,
        robot__start_time,
        robot__end_time,
        robot__k8s_env_name,
        robot__create_time,
        robot__update_time,

        customer__customer_id,
        customer__customer_name,
        customer__pid,
        customer__level,
        customer__region,
        customer__address,
        customer__website,
        customer__industry_id,
        customer__industry_name,
        customer__nature_code,
        customer__nature_name,
        customer__credit_code,
        customer__credit_name,
        customer__source_code,
        customer__source_name,
        customer__scale_code,
        customer__scale_name,
        customer__status_code,
        customer__status_name,
        customer__contact_code,
        customer__contact_name,
        customer__purchase_code,
        customer__purchase_name,
        customer__employment_code,
        customer__employment_name,
        customer__settlement_code,
        customer__settlement_name,
        customer__employer_num,

        tenant__tenant_id,
        tenant__tenant_name,
        tenant__tenant_type,
        tenant__tenant_type_name,
        tenant__vop_id,
        tenant__industry_id,
        tenant__industry_name,
        tenant__sub_sys,
        tenant__time_zone,
        tenant__net_env_id,
        tenant__mcs_area,
        tenant__device_num,
        tenant__region,
        tenant__country,
        tenant__province,
        tenant__city,
        tenant__address,
        tenant__contact,
        tenant__phone,
        tenant__phone_area_code,
        tenant__telephone,
        tenant__project_name,
        tenant__district,
        tenant__seller,
        tenant__email,
        tenant__boss_status,
        tenant__boss_status_name,
        tenant__roc_status,
        tenant__roc_status_name,
        tenant__charge_time,
        tenant__expired_time,
        tenant__logo,
        tenant__description,
        tenant__brand,
        tenant__is_need_vpn,
        tenant__service_address,
        tenant__create_time,

        asset_record_id,
        asset_record__action_type,
        asset_record__action_type_name,
        order_id,
        ext_data,
        asset_record__record_start_time,
        asset_record__record_end_time,
        asset_record__status,
        asset_record__status_name,
        asset_record__cause_type,
        asset_record__cause_type_name,
        staff_id,
        staff_name,
        event_time,
        asset_record__k8s_env_name,
        asset_record__create_time,
        asset_record__update_time,
        row_number() OVER (PARTITION BY robot__robot_id ORDER BY asset_record__update_time DESC) as rnk
    from dim_add_industry
)
insert overwrite table cdmdwm.dwm_pmd_robot_asset_s_d partition(dt)
    select
        robot__robot_id,
        robot__robot_name,
        robot__robot_type_id,
        robot__robot_type_inner_name,
        robot__robot_type_name,
        robot__asset_code,
        robot__asset_type,
        robot__asset_type_name,
        robot__product_type_code,
        robot__product_type_code_name,
        robot__product_id,
        robot__product_id_name,
        robot__asset_status,
        robot__asset_status_name,
        robot__status,
        robot__status_name,
        robot__robot_manufacturer_id,
        robot__robot_manufacturer_name,
        robot__model,
        robot__software_version,
        robot__hardware_version,
        robot__sku,
        robot__quality_date,
        robot__customer_quality_date,
        robot__product_date,
        robot__roc_delivery_status,
        robot__roc_delivery_status_name,
        robot__is_special_asset,
        robot__serial_number,
        robot__operating_status,
        robot__operating_status_name,
        robot__running_status,
        robot__running_status_name,
        robot__environment,
        robot__start_time,
        robot__end_time,
        robot__k8s_env_name,
        robot__create_time,
        robot__update_time,

        customer__customer_id,
        customer__customer_name,
        customer__pid,
        customer__level,
        customer__region,
        customer__address,
        customer__website,
        customer__industry_id,
        customer__industry_name,
        customer__nature_code,
        customer__nature_name,
        customer__credit_code,
        customer__credit_name,
        customer__source_code,
        customer__source_name,
        customer__scale_code,
        customer__scale_name,
        customer__status_code,
        customer__status_name,
        customer__contact_code,
        customer__contact_name,
        customer__purchase_code,
        customer__purchase_name,
        customer__employment_code,
        customer__employment_name,
        customer__settlement_code,
        customer__settlement_name,
        customer__employer_num,

        tenant__tenant_id,
        tenant__tenant_name,
        tenant__tenant_type,
        tenant__tenant_type_name,
        tenant__vop_id,
        tenant__industry_id,
        tenant__industry_name,
        tenant__sub_sys,
        tenant__time_zone,
        tenant__net_env_id,
        tenant__mcs_area,
        tenant__device_num,
        tenant__region,
        tenant__country,
        tenant__province,
        tenant__city,
        tenant__address,
        tenant__contact,
        tenant__phone,
        tenant__phone_area_code,
        tenant__telephone,
        tenant__project_name,
        tenant__district,
        tenant__seller,
        tenant__email,
        tenant__boss_status,
        tenant__boss_status_name,
        tenant__roc_status,
        tenant__roc_status_name,
        tenant__charge_time,
        tenant__expired_time,
        tenant__logo,
        tenant__description,
        tenant__brand,
        tenant__is_need_vpn,
        tenant__service_address,
        tenant__create_time,

        asset_record_id,
        asset_record__action_type,
        asset_record__action_type_name,
        order_id,
        ext_data,
        asset_record__record_start_time,
        asset_record__record_end_time,
        asset_record__status,
        asset_record__status_name,
        asset_record__cause_type,
        asset_record__cause_type_name,
        staff_id,
        staff_name,
        event_time,
        asset_record__k8s_env_name,
        asset_record__create_time,
        asset_record__update_time,
        '${e_dt_var}' as dt
    from remove_duplict where rnk = 1;