set hive.exec.dynamic.partition.mode = nonstrict;
set hive.merge.mapfiles = true;
set hive.merge.mapredfiles = true;
set hive.exec.max.dynamic.partitions = 60000;
set mapreduce.job.queuename=root.users.hive;

with test as (
    SELECT
        event_id,
        event_type_id,
        event_type_name_cn,
        event_type_name_en,
        rcu_id,
        device_id,
        event_time,
        event_level,
        event_details,
        ext_data,
        event_pic_url,
        robot_location_info,
        create_time,
        update_time,
        read_flag,
        read_flag_name,
        remark,
        msg_type_id,
        k8s_env_name,
        sv_agent_id,
--   tenant dim
        tenant__tenant_id,
        tenant__tenant_name,
        tenant__tenant_type,
        tenant__industry_id,
        tenant__sub_sys,
        tenant__time_zone,
        tenant__net_env_id,
        tenant__mcs_area,
        tenant__device_num,
        tenant__region,
        tenant__address,
        tenant__contact,
        tenant__phone,
        tenant__telephone,
        tenant__seller,
        tenant__email,
        tenant__status,
        tenant__status_name,
        tenant__charge_time,
        tenant__expired_time,
        tenant__logo,
        tenant__description,
        tenant__brand,
        tenant__is_need_vpn,
        tenant__create_time,
        tenant__industry_name,
--  robot dim
        robot__robot_id,
        robot__robot_name,
        robot__robot_type_id,
        robot__robot_type_inner_name,
        robot__robot_type_name,
        robot__asset_code,
        robot__asset_type,
        robot__product_type_code,
        robot__product_type_code_name,
        robot__product_id,
        robot__product_id_name,
        robot__assets_status,
        robot__assets_status_name,
        robot__status,
        robot__status_name,
        robot__robot_manufacturer_id,
        robot__robot_manufacturer_name,
        robot__model,
        robot__os,
        robot__version_code,
        robot__software_version,
        robot__hardware_version,
        robot__head_url,
        robot__regist_time,
        robot__bind_status,
        robot__bind_status_name,
        robot__is_hi_service,
        robot__is_privacy_enhance,
        robot__remind_policy_id,
        robot__sku,
        robot__quality_date,
        robot__customer_quality_date,
        robot__out_type_state,
        robot__out_type_state_name,
        robot__product_date,
        robot__in_stock_date,
        robot__out_stock_date,
        robot__in_stock_staff_id,
        robot__in_stock_staff_name,
        robot__out_stock_staff_id,
        robot__out_stock_staff_name,
        robot__robot_note,
        robot__description,
        robot__create_time,
--customer dim
        customer__customer_id,
        customer__customer_name,
        customer__pid,
        customer__level,
        customer__region,
        customer__address,
        customer__website,
        customer__nature_code,
        customer__nature_name,
        customer__credit_code,
        customer__credit_name,
        customer__source_code,
        customer__source_name,
        customer__scale_code,
        customer__scale_name,
        customer__status_code,
        customer__status_name,
        customer__contact_code,
        customer__contact_name,
        customer__purchase_code,
        customer__purchase_name,
        customer__employment_code,
        customer__employment_name,
        customer__settlement_code,
        customer__settlement_name,
        customer__employer_num,
        customer__category_code,
        customer__category_name,
        customer__create_time,
        row_number() over (partition by robot__robot_id order by robot__robot_id,event_time  ) as rnk
    from cdmdwm.dwm_omd_robot_monitor_event_i_d
    WHERE dt='2021-07-13' and
            event_type_id in ('10000','10001') AND
            (trim(event_details)!='设备上线(自动生成)'
                or robot__robot_id in ('M2T2018120243','M2T2018120264','GS-0001-0001-2406-0014','GS-0032-0001-2408-0001',
                                        'GINLITXR-1LXXXXXXXXXGNL08S2121000087','GINGERXR-1-A2-TX2XXXGIN01S2036000002',
                                        'GINGERXR-1##########GIN01S2027000003','GINGERXR-1##########GIN01S2030000012',
                                        'AP990438A00Y69100472','AP990396A14Y99100011','AP990396A12Y96100066','AP990396A12Y96100021',
                                        'AP990396A12Y96100005','AP990396A08Y75100085','AP990396A07Y71300019',
                                        '94-c6-91-16-15-27','864972049983492','862851030117439','862851030081064',
                                        '862851030044971','862851030018496','355929090210130'))
    order by robot__robot_id , event_time
)

insert overwrite table cdmdws.dws_omd_robot_statistic_i_d  partition(dt)
select
    rcu_id,
    device_id,
    k8s_env_name,
    sv_agent_id,
--   tenant dim
    tenant__tenant_id,
    tenant__tenant_name,
    tenant__tenant_type,
    tenant__industry_id,
    tenant__sub_sys,
    tenant__time_zone,
    tenant__net_env_id,
    tenant__mcs_area,
    tenant__device_num,
    tenant__region,
    tenant__address,
    tenant__contact,
    tenant__phone,
    tenant__telephone,
    tenant__seller,
    tenant__email,
    tenant__status,
    tenant__status_name,
    tenant__charge_time,
    tenant__expired_time,
    tenant__logo,
    tenant__description,
    tenant__brand,
    tenant__is_need_vpn,
    tenant__create_time,
    tenant__industry_name,
--  robot dim
    robot__robot_id,
    robot__robot_name,
    robot__robot_type_id,
    robot__robot_type_inner_name,
    robot__robot_type_name,
    robot__asset_code,
    robot__asset_type,
    robot__product_type_code,
    robot__product_type_code_name,
    robot__product_id,
    robot__product_id_name,
    robot__assets_status,
    robot__assets_status_name,
    robot__status,
    robot__status_name,
    robot__robot_manufacturer_id,
    robot__robot_manufacturer_name,
    robot__model,
    robot__os,
    robot__version_code,
    robot__software_version,
    robot__hardware_version,
    robot__head_url,
    robot__regist_time,
    robot__bind_status,
    robot__bind_status_name,
    robot__is_hi_service,
    robot__is_privacy_enhance,
    robot__remind_policy_id,
    robot__sku,
    robot__quality_date,
    robot__customer_quality_date,
    robot__out_type_state,
    robot__out_type_state_name,
    robot__product_date,
    robot__in_stock_date,
    robot__out_stock_date,
    robot__in_stock_staff_id,
    robot__in_stock_staff_name,
    robot__out_stock_staff_id,
    robot__out_stock_staff_name,
    robot__robot_note,
    robot__description,
    robot__create_time,
--customer dim
    customer__customer_id,
    customer__customer_name,
    customer__pid,
    customer__level,
    customer__region,
    customer__address,
    customer__website,
    customer__nature_code,
    customer__nature_name,
    customer__credit_code,
    customer__credit_name,
    customer__source_code,
    customer__source_name,
    customer__scale_code,
    customer__scale_name,
    customer__status_code,
    customer__status_name,
    customer__contact_code,
    customer__contact_name,
    customer__purchase_code,
    customer__purchase_name,
    customer__employment_code,
    customer__employment_name,
    customer__settlement_code,
    customer__settlement_name,
    customer__employer_num,
    customer__category_code,
    customer__category_name,
    customer__create_time,
    last_status,
    robot_last_status_name,
    online_time,
    offline_times,
    dt
from (select rcu_id,
             device_id,
             k8s_env_name,
             sv_agent_id,
--   tenant dim
             tenant__tenant_id,
             tenant__tenant_name,
             tenant__tenant_type,
             tenant__industry_id,
             tenant__sub_sys,
             tenant__time_zone,
             tenant__net_env_id,
             tenant__mcs_area,
             tenant__device_num,
             tenant__region,
             tenant__address,
             tenant__contact,
             tenant__phone,
             tenant__telephone,
             tenant__seller,
             tenant__email,
             tenant__status,
             tenant__status_name,
             tenant__charge_time,
             tenant__expired_time,
             tenant__logo,
             tenant__description,
             tenant__brand,
             tenant__is_need_vpn,
             tenant__create_time,
             tenant__industry_name,
--  robot dim
             robot__robot_id,
             robot__robot_name,
             robot__robot_type_id,
             robot__robot_type_inner_name,
             robot__robot_type_name,
             robot__asset_code,
             robot__asset_type,
             robot__product_type_code,
             robot__product_type_code_name,
             robot__product_id,
             robot__product_id_name,
             robot__assets_status,
             robot__assets_status_name,
             robot__status,
             robot__status_name,
             robot__robot_manufacturer_id,
             robot__robot_manufacturer_name,
             robot__model,
             robot__os,
             robot__version_code,
             robot__software_version,
             robot__hardware_version,
             robot__head_url,
             robot__regist_time,
             robot__bind_status,
             robot__bind_status_name,
             robot__is_hi_service,
             robot__is_privacy_enhance,
             robot__remind_policy_id,
             robot__sku,
             robot__quality_date,
             robot__customer_quality_date,
             robot__out_type_state,
             robot__out_type_state_name,
             robot__product_date,
             robot__in_stock_date,
             robot__out_stock_date,
             robot__in_stock_staff_id,
             robot__in_stock_staff_name,
             robot__out_stock_staff_id,
             robot__out_stock_staff_name,
             robot__robot_note,
             robot__description,
             robot__create_time,
--customer dim
             customer__customer_id,
             customer__customer_name,
             customer__pid,
             customer__level,
             customer__region,
             customer__address,
             customer__website,
             customer__nature_code,
             customer__nature_name,
             customer__credit_code,
             customer__credit_name,
             customer__source_code,
             customer__source_name,
             customer__scale_code,
             customer__scale_name,
             customer__status_code,
             customer__status_name,
             customer__contact_code,
             customer__contact_name,
             customer__purchase_code,
             customer__purchase_name,
             customer__employment_code,
             customer__employment_name,
             customer__settlement_code,
             customer__settlement_name,
             customer__employer_num,
             customer__category_code,
             customer__category_name,
             customer__create_time,
             to_date(event_time) as dt,
             last_status,
             case
                 when last_status = 10000 then '在线'
                 when last_status = 10001 then '离线'
                 else '未知'
                 end             as robot_last_status_name,
             sum(deta_time)      as online_time,
             count(1)            as offline_times
      from (
               select case
                          when (event_type_id = '10000' and ntype = '10001' and ntime is not null)
                              then cast(unix_timestamp(ntime) as int) - cast(unix_timestamp(event_time) as int)
                          when (event_type_id = '10000' and ntype is null)
                              then cast(unix_timestamp(date_add(to_date(event_time), 1)) as int) -
                                   cast(unix_timestamp(event_time) as int)
                          else 0
                          end as deta_time,
                      tmp.*
               from (
                        select *,
                               lead(event_time, 1, NULL)
                                    over (partition by robot__robot_id order by event_time)                         as ntime,
                               lead(event_type_id, 1, null)
                                    over (partition by robot__robot_id order by event_time)                         as ntype,
                               first_value(event_type_id)
                                           over (partition by robot__robot_id order by event_time desc)             as last_status
                        from test
                    ) as tmp
               order by robot__robot_id, event_time
           ) as tmp2
      group by rcu_id,
               device_id,
               k8s_env_name,
               sv_agent_id,
--   tenant dim
               tenant__tenant_id,
               tenant__tenant_name,
               tenant__tenant_type,
               tenant__industry_id,
               tenant__sub_sys,
               tenant__time_zone,
               tenant__net_env_id,
               tenant__mcs_area,
               tenant__device_num,
               tenant__region,
               tenant__address,
               tenant__contact,
               tenant__phone,
               tenant__telephone,
               tenant__seller,
               tenant__email,
               tenant__status,
               tenant__status_name,
               tenant__charge_time,
               tenant__expired_time,
               tenant__logo,
               tenant__description,
               tenant__brand,
               tenant__is_need_vpn,
               tenant__create_time,
               tenant__industry_name,
--  robot dim
               robot__robot_id,
               robot__robot_name,
               robot__robot_type_id,
               robot__robot_type_inner_name,
               robot__robot_type_name,
               robot__asset_code,
               robot__asset_type,
               robot__product_type_code,
               robot__product_type_code_name,
               robot__product_id,
               robot__product_id_name,
               robot__assets_status,
               robot__assets_status_name,
               robot__status,
               robot__status_name,
               robot__robot_manufacturer_id,
               robot__robot_manufacturer_name,
               robot__model,
               robot__os,
               robot__version_code,
               robot__software_version,
               robot__hardware_version,
               robot__head_url,
               robot__regist_time,
               robot__bind_status,
               robot__bind_status_name,
               robot__is_hi_service,
               robot__is_privacy_enhance,
               robot__remind_policy_id,
               robot__sku,
               robot__quality_date,
               robot__customer_quality_date,
               robot__out_type_state,
               robot__out_type_state_name,
               robot__product_date,
               robot__in_stock_date,
               robot__out_stock_date,
               robot__in_stock_staff_id,
               robot__in_stock_staff_name,
               robot__out_stock_staff_id,
               robot__out_stock_staff_name,
               robot__robot_note,
               robot__description,
               robot__create_time,
--customer dim
               customer__customer_id,
               customer__customer_name,
               customer__pid,
               customer__level,
               customer__region,
               customer__address,
               customer__website,
               customer__nature_code,
               customer__nature_name,
               customer__credit_code,
               customer__credit_name,
               customer__source_code,
               customer__source_name,
               customer__scale_code,
               customer__scale_name,
               customer__status_code,
               customer__status_name,
               customer__contact_code,
               customer__contact_name,
               customer__purchase_code,
               customer__purchase_name,
               customer__employment_code,
               customer__employment_name,
               customer__settlement_code,
               customer__settlement_name,
               customer__employer_num,
               customer__category_code,
               customer__category_name,
               customer__create_time,
               to_date(event_time),
               last_status
     ) as t3