CREATE EXTERNAL TABLE cdmdim.dim_umd_tenant_sh_d (
    tenant_id string comment '租户code码',
    tenant_name	string comment '租户名称',
    tenant_type	int comment '租户类型',
    tenant_type_name string comment '租户类型名称: 0长租、1短租、2试用、3售卖、4测试',
    vop_id string comment '关联的虚拟运营商id',
    customer_id	string comment '租户所属的客户id',
    industry_id	string comment '租户所属行业id',
    sub_sys	string comment '子系统',
    time_zone string comment '时区',
    net_env_id string comment '网络环境',
    mcs_area string	comment 'vpn区域代码',
    device_num int comment 'vpn限制设备数',
    region string comment '地区',
    country string COMMENT '国家',
    province string COMMENT '省份',
    city string COMMENT '城市',
    address	string comment '地址',
    contact	string comment '租户联系人',
    phone string comment '联系电话',
    phone_area_code string COMMENT '手机区域编码',
    telephone string comment '联系电话',
    project_name string COMMENT '项目名称',
    district string comment '所属区域地图',
    seller string comment '销售人员',
    email string comment '邮箱地址',
    boss_status int comment '租户状态: 1-有效 9-删除',
    boss_status_name string comment '租户状态',
    roc_status int comment '租户roc状态: -1-删除;0-正常;1-待开通;2-锁定',
    roc_status_name string comment '租户roc状态',
    charge_time	string comment '计费开始时间',
    expired_time string	comment '租户过期时间',
    logo string	comment '租户logo地址',
    description	string	comment '租户简要描述',
    brand string comment '客户品牌化参数',
    is_need_vpn	int comment '是否需要VPN: 0-不需要;1-需要',
    service_address string COMMENT '服务地址',
    create_time	string comment '租户创建时间',
    update_time	string comment '租户更新时间',
    start_time string comment '开始时间',
    end_time string comment '结束时间',
    k8s_env_name string comment '环境时间'
)COMMENT 'tenant 租户明细表'
partitioned by(dt string comment '日期')
STORED AS parquet;