package bean;

public class PickOrderDetail {
    public String pickOrderCode;
    public Long pickOrderId;
    public String pickOrderType;
    public Integer pickOrderStatus;
    public String materials;
    public String remark;
    public String creator;
    public Long createdAt;
    public String operator;
    public Long updatedAt;

//    public String alternativeMaterialFlag;
//    public String batchCode;
//    public Long createdAt;
//    public String creator;
//    public String inputOrAlternativeMaterialId;
//    public String inputProcessCode;
//    public String inputProcessId;
//    public String inputProcessName;
//    public Integer line;
//    public String mainOutputBatchNumber;
//    public String material;
//    public String operator;
//    public String pickOrderCode;
//    public String pickOrderDetailId;
//    public Long pickOrderId;
//    public String pickOrderIssuedAmount;
//    public Integer pickOrderStatus;
//    public String pickOrderType;
//    public String productionDepartment;
//    public String receivePickAmount;
//    public String remark;
//    public String requestPickAmount;
//    public String requirementTime;
//    public String seq;
//    public String sourceWarehouse;
//    public String sourceWarehouseId;
//    public String sourceWarehouseName;
//    public String supplierList;
//    public String targetWarehouse;
//    public String targetWarehouseId;
//    public String targetWarehouseName;
//    public String transferIssuedAmount;
//    public String transferOrderVO;
//    public Long updatedAt;
//    public String warehouseIssuedAmount;
//    public String workCenter;
//    public String workOrderCode;
//    public String workOrderId;
}
