set hive.exec.dynamic.partition.mode = nonstrict;
set hive.merge.mapfiles = true;
set hive.merge.mapredfiles = true;
set hive.exec.max.dynamic.partitions = 60000;
set spark.executor.memory = 4G;
set spark.locality.wait = 10;
set mapreduce.job.queuename=root.users.liuhao;


with union_question_id as (
    select
        question_id
    from (
         select question_id from cdmdwd.dwd_harix_cmd_rcu_record_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_asr_recognize_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_asr_cmd_asr_hit_domain_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_asr_send_txt_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_reception_send_txt_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_robot_send_txt_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_nlp_cmd_nlu_recognize_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_asr_send_qa_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_reception_send_qa_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_robot_send_qa_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_hi_intelligence_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
         union all
         select question_id from cdmdwd.dwd_harix_cmd_hi_send_qa_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t where trim(t.question_id) != '' group by question_id
),
audio_process_tmp as (
    select
        t1.question_id,
        coalesce(if(nvl(t2.robot_id,'') = '',null,t2.robot_id),
                 if(nvl(t3.robot_id,'') = '',null,t3.robot_id),
                 if(nvl(t4.robot_id,'') = '',null,t4.robot_id),
                 if(nvl(t5.robot_id,'') = '',null,t5.robot_id),
                 if(nvl(t6.robot_id,'') = '',null,t6.robot_id),
                 if(nvl(t7.robot_id,'') = '',null,t7.robot_id),
                 if(nvl(t8.robot_id,'') = '',null,t8.robot_id),
                 if(nvl(t9.robot_id,'') = '',null,t9.robot_id),
                 if(nvl(t10.robot_id,'') = '',null,t10.robot_id),
                 if(nvl(t11.robot_id,'') = '',null,t11.robot_id),
                 if(nvl(t12.robot_id,'') = '',null,t12.robot_id),
                 if(nvl(t13.robot_id,'') = '',null,t13.robot_id),'') as robot_id,
        coalesce(if(nvl(t2.rcu_audio,'') = '',null,t2.rcu_audio),
                 if(nvl(t3.rcu_audio,'') = '',null,t3.rcu_audio),
                 if(nvl(t5.rcu_audio,'') = '',null,t5.rcu_audio),
                 if(nvl(t6.rcu_audio,'') = '',null,t6.rcu_audio),
                 if(nvl(t7.rcu_audio,'') = '',null,t7.rcu_audio),
                 if(nvl(t9.rcu_audio,'') = '',null,t9.rcu_audio),
                 if(nvl(t10.rcu_audio,'') = '',null,t10.rcu_audio),
                 if(nvl(t11.rcu_audio,'') = '',null,t11.rcu_audio),
                 if(nvl(t13.rcu_audio,'') = '',null,t13.rcu_audio),'') as rcu_audio,
        coalesce(t2.is_noise,t3.is_noise,-99999998) as is_noise,
        coalesce(if(nvl(t2.robot_account_id,'') = '',null,t2.robot_account_id),
                 if(nvl(t3.robot_account_id,'') = '',null,t3.robot_account_id),
                 if(nvl(t4.robot_account_id,'') = '',null,t4.robot_account_id),
                 if(nvl(t5.robot_account_id,'') = '',null,t5.robot_account_id),
                 if(nvl(t6.robot_account_id,'') = '',null,t6.robot_account_id),
                 if(nvl(t7.robot_account_id,'') = '',null,t7.robot_account_id),
                 if(nvl(t8.robot_account_id,'') = '',null,t8.robot_account_id),
                 if(nvl(t9.robot_account_id,'') = '',null,t9.robot_account_id),
                 if(nvl(t10.robot_account_id,'') = '',null,t10.robot_account_id),
                 if(nvl(t11.robot_account_id,'') = '',null,t11.robot_account_id),
                 if(nvl(t12.robot_account_id,'') = '',null,t12.robot_account_id),
                 if(nvl(t13.robot_account_id,'') = '',null,t13.robot_account_id),'') as robot_account_id,
        coalesce(if(nvl(t2.service_code,'') = '',null,t2.service_code),
                 if(nvl(t3.service_code,'') = '',null,t3.service_code),
                 if(nvl(t4.service_code,'') = '',null,t4.service_code),
                 if(nvl(t5.service_code,'') = '',null,t5.service_code),
                 if(nvl(t6.service_code,'') = '',null,t6.service_code),
                 if(nvl(t7.service_code,'') = '',null,t7.service_code),
                 if(nvl(t9.service_code,'') = '',null,t9.service_code),
                 if(nvl(t10.service_code,'') = '',null,t10.service_code),
                 if(nvl(t11.service_code,'') = '',null,t11.service_code),
                 if(nvl(t12.service_code,'') = '',null,t12.service_code),
                 if(nvl(t13.service_code,'') = '',null,t13.service_code),'') as service_code,
        coalesce(if(nvl(t2.tenant_id,'') = '',null,t2.tenant_id),
                 if(nvl(t3.tenant_id,'') = '',null,t3.tenant_id),
                 if(nvl(t4.tenant_id,'') = '',null,t4.tenant_id),
                 if(nvl(t5.tenant_id,'') = '',null,t5.tenant_id),
                 if(nvl(t6.tenant_id,'') = '',null,t6.tenant_id),
                 if(nvl(t7.tenant_id,'') = '',null,t7.tenant_id),
                 if(nvl(t9.tenant_id,'') = '',null,t9.tenant_id),
                 if(nvl(t10.tenant_id,'') = '',null,t10.tenant_id),
                 if(nvl(t11.tenant_id,'') = '',null,t11.tenant_id),
                 if(nvl(t12.tenant_id,'') = '',null,t12.tenant_id),
                 if(nvl(t13.tenant_id,'') = '',null,t13.tenant_id),'') as tenant_id,
        coalesce(t2.app_type,t3.app_type,'') as app_type,
        coalesce(if(nvl(t2.robot_type,'') = '',null,t2.robot_type),
                 if(nvl(t3.robot_type,'') = '',null,t3.robot_type),
                 if(nvl(t4.robot_type,'') = '',null,t4.robot_type),
                 if(nvl(t5.robot_type,'') = '',null,t5.robot_type),
                 if(nvl(t6.robot_type,'') = '',null,t6.robot_type),
                 if(nvl(t7.robot_type,'') = '',null,t7.robot_type),
                 if(nvl(t8.robot_type,'') = '',null,t8.robot_type),
                 if(nvl(t9.robot_type,'') = '',null,t9.robot_type),
                 if(nvl(t10.robot_type,'') = '',null,t10.robot_type),
                 if(nvl(t11.robot_type,'') = '',null,t11.robot_type),
                 if(nvl(t12.robot_type,'') = '',null,t12.robot_type),
                 if(nvl(t13.robot_type,'') = '',null,t13.robot_type),'') as robot_type,
        coalesce(t2.audio_record_type,t3.audio_record_type,'') as audio_record_type,
        coalesce(if(nvl(t2.qa_flag,'') = '',null,t2.qa_flag),
                 if(nvl(t3.qa_flag,'') = '',null,t3.qa_flag),
                 if(nvl(t5.qa_flag,'') = '',null,t5.qa_flag),
                 if(nvl(t6.qa_flag,'') = '',null,t6.qa_flag),
                 if(nvl(t7.qa_flag,'') = '',null,t7.qa_flag),
                 if(nvl(t9.qa_flag,'') = '',null,t9.qa_flag),
                 if(nvl(t10.qa_flag,'') = '',null,t10.qa_flag),
                 if(nvl(t11.qa_flag,'') = '',null,t11.qa_flag),
                 if(nvl(t13.qa_flag,'') = '',null,t13.qa_flag),'') as qa_flag,
        nvl(t2.duration,-99999998) as duration,
        nvl(t2.dialect,'') as dialect,
        nvl(t2.audio_sample_rate,'') as audio_sample_rate,
        coalesce(if(nvl(t2.asr_vendor,'') = '',null,t2.asr_vendor),
                 if(nvl(t3.asr_vendor,'') = '',null,t3.asr_vendor),
                 if(nvl(t4.asr_vendor,'') = '',null,t4.asr_vendor),'') as asr_vendor,
        nvl(t2.format,'') as format,
        nvl(t2.channel,'') as channel,
        coalesce(if(nvl(t8.sv_agent_id,'') = '',null,t8.sv_agent_id),
                 if(nvl(t2.sv_agent_id,'') = '',null,t2.sv_agent_id),
                 if(nvl(t3.sv_agent_id,'') = '',null,t3.sv_agent_id),
                 if(nvl(t4.sv_agent_id,'') = '',null,t4.sv_agent_id),'') as sv_agent_id,
        nvl(t2.k8s_svc_name,'') as rcu_record_k8s_svc_name,
        nvl(t2.k8s_env_name,'') as rcu_record_k8s_env_name,
        nvl(t2.event_time,'') as rcu_record_event_time,
        case when nvl(t2.question_id,'') != '' then 1
             else 0
            end as is_rcu_record,
        coalesce(if(nvl(t3.vpr_id,'') = '',null,t3.vpr_id),
                 if(nvl(t4.vpr_id,'') = '',null,t4.vpr_id),
                 if(nvl(t8.vpr_id,'') = '',null,t8.vpr_id),'') as vpr_id,
        coalesce(if(nvl(t9.question_text,'') = '',null,t9.question_text),
                 if(nvl(t10.question_text,'') = '',null,t10.question_text),
                 if(nvl(t11.question_text,'') = '',null,t11.question_text),
                 if(nvl(t13.question_text,'') = '',null,t13.question_text),
                 if(nvl(t3.question_text,'') = '',null,t3.question_text),
                 if(nvl(t4.question_text,'') = '',null,t4.question_text),
                 if(nvl(t5.question_text,'') = '',null,t5.question_text),
                 if(nvl(t6.question_text,'') = '',null,t6.question_text),
                 if(nvl(t7.question_text,'') = '',null,t7.question_text),
                 if(nvl(t8.question_text,'') = '',null,t8.question_text),'') as question_text,
        nvl(t3.audio_length,-99999998) as audio_length,
        nvl(t3.asr_vendor_delay,-99999998) as asr_vendor_delay,
        nvl(t3.rcc_delay,-99999998) as rcc_delay,
        nvl(t3.forward_delay,-99999998) as forward_delay,
        nvl(t3.k8s_svc_name,'') as asr_recognize_k8s_svc_name,
        nvl(t3.k8s_env_name,'') as asr_recognize_k8s_env_name,
        nvl(t3.event_time,'') as asr_recognize_event_time,
        case when nvl(t3.question_id,'') != '' then 1
             else 0
        end as is_asr_recognize,
        nvl(t4.asr_domain,'') as asr_domain,
        nvl(t4.asr_third_total,-99999998) as asr_third_total,
        nvl(t4.asr_start,'') as asr_start,
        nvl(t4.asr_end,'') as asr_end,
        nvl(t4.nlufwd,'') as nlufwd,
        nvl(t4.wake_status,-99999998) as wake_status,
        nvl(t4.wake_status_name,'未知') as wake_status_name,
        nvl(t4.nlp_total,-99999998) as nlp_total,
        nvl(t4.gap,-99999998) as gap,
        nvl(t4.vocal_total,-99999998) as vocal_total,
        nvl(t4.last_pre_end_start,'') as last_pre_end_start,
        nvl(t4.asrctrl_duration,-99999998) as asrctrl_duration,
        nvl(t4.x_b3_traceid,'') as x_b3_traceid,
        nvl(t4.asrctrl_inner,-99999998) as asrctrl_inner,
        nvl(t4.caller,'') as caller,
        nvl(t4.is_pre_end,-99999998) as is_pre_end,
        nvl(t4.asrctrl_robot_skill_total,-99999998) as asrctrl_robot_skill_total,
        nvl(t4.asr_nlp_total,-99999998) as asr_nlp_total,
        nvl(t4.audio_size,-99999998) as audio_size,
        nvl(t4.k8s_svc_name,'') as asr_domain_k8s_svc_name,
        nvl(t4.k8s_env_name,'') as asr_domain_k8s_env_name,
        nvl(t4.event_time,'') as asr_domain_event_time,
        case when nvl(t4.question_id,'') != '' then 1
             else 0
        end as is_asr_domain,
        coalesce(if(nvl(t5.hi_status,-99999998) = -99999998,null,t5.hi_status),
                 if(nvl(t9.hi_status,-99999998) = -99999998,null,t9.hi_status),-99999998) as is_hi_online,
        coalesce(if(nvl(t5.latitude,'') = '',null,t5.latitude),
                 if(nvl(t9.latitude,'') = '',null,t9.latitude),'') as latitude,
        coalesce(if(nvl(t5.longitude,'') = '',null,t5.longitude),
                 if(nvl(t9.longitude,'') = '',null,t9.longitude),'') as longitude,
        nvl(t5.send_delay,-99999998) as txt_send_delay,
        nvl(t5.queue_delay,-99999998) as txt_queue_delay,
        nvl(t5.total_delay,-99999998) as txt_total_delay,
        nvl(t5.k8s_svc_name,'') as asr_text_k8s_svc_name,
        nvl(t5.k8s_env_name,'') as asr_text_k8s_env_name,
        nvl(t5.event_time,'') as asr_text_event_time,
        case when nvl(t5.question_id,'') != '' then 1
             else 0
            end as is_asr_text,
        nvl(t6.k8s_svc_name,'') as reception_text_k8s_svc_name,
        nvl(t6.k8s_env_name,'') as reception_text_k8s_env_name,
        nvl(t6.event_time,'') as reception_text_event_time,
        case when nvl(t6.question_id,'') != '' then 1
             else 0
            end as is_reception_text,
        nvl(t7.harix_switch_id,'') as harix_switch_id,
        nvl(t7.type_url,'') as type_url,
        coalesce(if(nvl(t9.question_language,'') = '',null,t9.question_language),
                if(nvl(t10.question_language,'') = '',null,t10.question_language),
                if(nvl(t11.question_language,'') = '',null,t11.question_language),
                if(nvl(t13.question_language,'') = '',null,t13.question_language),
                if(nvl(t6.question_language,'') = '',null,t6.question_language),
                if(nvl(t7.question_language,'') = '',null,t7.question_language),'') as question_language,
        nvl(t7.msg_from,'') as robot_text_msg_from,
        nvl(t7.msg_send_name,'') as robot_text_msg_send_name,
        nvl(t7.msg_id,'') as robot_text_msg_id,
        nvl(t7.msg_receive_name,'') as robot_text_msg_receive_name,
        nvl(t7.msg_type,'') as robot_text_msg_type,
        nvl(t7.msg_dest,'') as robot_text_msg_dest,
        nvl(t7.k8s_svc_name,'') as robot_text_k8s_svc_name,
        nvl(t7.k8s_env_name,'') as robot_text_k8s_env_name,
        nvl(t7.event_time,'') as robot_text_event_time,
        case when nvl(t7.question_id,'') != '' then 1
             else 0
            end as is_robot_text,
        nvl(t8.sv_agent_name,'') as sv_agent_name,
        nvl(t8.algo,'') as algo,
        nvl(t8.cost,-99999998) as cost,
        nvl(t8.matched_template,'') as matched_template,
        nvl(t8.domain_id,'') as domain_id,
        nvl(t8.domain_name,'') as domain_name,
        nvl(t8.intent_id,'') as intent_id,
        coalesce(if(nvl(t8.intent_name,'') = '',null,t8.intent_name),'') as intent_name,
        nvl(t8.env_info,'') as env_info,
        nvl(t8.before_context,'') as before_context,
        nvl(t8.in_context,'') as in_context,
        nvl(t8.out_context,'') as out_context,
        nvl(t8.param_info,'') as param_info,
        nvl(t8.parameters,'') as parameters,
        nvl(t8.qa_result,'') as qa_result,
        if(nvl(t8.fqa_cate_id,'0') = '0','',t8.fqa_cate_id) as fqa_cate_id,
        if(nvl(t8.user_qa_cate_id,'0') = '0','',t8.user_qa_cate_id) as user_qa_cate_id,
        nvl(t8.question_group_id,'') as question_group_id,
        nvl(t8.sim_question_score,0.0000000000000001) as sim_question_score,
        case when coalesce(if(nvl(t9.answer_text,'') = '',null,t9.answer_text),
                           if(nvl(t10.answer_text,'') = '',null,t10.answer_text),
                           if(nvl(t11.answer_text,'') = '',null,t11.answer_text),
                           if(nvl(t13.answer_text,'') = '',null,t13.answer_text),'') != '' then
                 coalesce(if(nvl(t9.answer_text,'') = '',null,t9.answer_text),
                          if(nvl(t10.answer_text,'') = '',null,t10.answer_text),
                          if(nvl(t11.answer_text,'') = '',null,t11.answer_text),
                          if(nvl(t13.answer_text,'') = '',null,t13.answer_text),'')
                 else nvl(t8.answer_text,'')
        end as answer_text,
        nvl(t8.answer_text,'') as sv_answer_text,
        coalesce(if(nvl(t9.answer_language,'') = '',null,t9.answer_language),
                 if(nvl(t10.answer_language,'') = '',null,t10.answer_language),
                 if(nvl(t11.answer_language,'') = '',null,t11.answer_language),
                 if(nvl(t13.answer_language,'') = '',null,t13.answer_language),'') as answer_language,
        nvl(t8.session_id,'') as session_id,
        coalesce(if(nvl(t8.qa_from,'') = '',null,t8.qa_from),
                 if(nvl(t9.qa_from,'') = '',null,t9.qa_from),'') as qa_from,
        nvl(t8.supplier,'') as supplier,
        nvl(t8.supplier_type,'') as supplier_type,
        nvl(t8.third_cost,-99999998) as third_cost,
        nvl(t8.third_session_id,'') as third_session_id,
        nvl(t8.k8s_svc_name,'') as nlu_k8s_svc_name,
        nvl(t8.k8s_env_name,'') as nlu_k8s_env_name,
        nvl(t8.event_time,'') as nlu_event_time,
        case when nvl(t8.question_id,'') != '' then 1
             else 0
        end as is_nlp,
        cast(nvl(t9.confidence,0.0) as double) as confidence,
        nvl(t9.send_delay,-99999998) as qa_send_delay,
        nvl(t9.queue_delay,-99999998) as qa_queue_delay,
        nvl(t9.total_delay,-99999998) as qa_total_delay,
        nvl(t9.msg_from,'') as asr_qa_msg_from,
        coalesce(if(nvl(t9.tts_step,'') = '',null,t9.tts_step),
                 if(nvl(t10.tts_step,'') = '',null,t10.tts_step),
                 if(nvl(t11.tts_step,'') = '',null,t11.tts_step),
                 if(nvl(t13.tts_step,'') = '',null,t13.tts_step),'') as tts_step,
        coalesce(if(nvl(t9.tts_emoji,'') = '',null,t9.tts_emoji),
                 if(nvl(t10.tts_emoji,'') = '',null,t10.tts_emoji),
                 if(nvl(t11.tts_emoji,'') = '',null,t11.tts_emoji),
                 if(nvl(t13.tts_emoji,'') = '',null,t13.tts_emoji),'') as tts_emoji,
        coalesce(if(nvl(t9.tts_payload,'') = '',null,t9.tts_payload),
                 if(nvl(t10.tts_payload,'') = '',null,t10.tts_payload),
                 if(nvl(t11.tts_payload,'') = '',null,t11.tts_payload),
                 if(nvl(t13.tts_payload,'') = '',null,t13.tts_payload),'') as tts_payload,
        coalesce(if(nvl(t9.action_duration,'') = '',null,t9.action_duration),
                 if(nvl(t10.action_duration,'') = '',null,t10.action_duration),
                 if(nvl(t11.action_duration,'') = '',null,t11.action_duration),
                 if(nvl(t13.action_duration,'') = '',null,t13.action_duration),'') as action_duration,
        coalesce(if(nvl(t9.action_frame_no,'') = '',null,t9.action_frame_no),
                 if(nvl(t10.action_frame_no,'') = '',null,t10.action_frame_no),
                 if(nvl(t11.action_frame_no,'') = '',null,t11.action_frame_no),
                 if(nvl(t13.action_frame_no,'') = '',null,t13.action_frame_no),'') as action_frame_no,
        coalesce(if(nvl(t9.action_play_type,'') = '',null,t9.action_play_type),
                 if(nvl(t10.action_play_type,'') = '',null,t10.action_play_type),
                 if(nvl(t11.action_play_type,'') = '',null,t11.action_play_type),
                 if(nvl(t13.action_play_type,'') = '',null,t13.action_play_type),'') as action_play_type,
        coalesce(if(nvl(t9.action_video_url,'') = '',null,t9.action_video_url),
                 if(nvl(t10.action_video_url,'') = '',null,t10.action_video_url),
                 if(nvl(t11.action_video_url,'') = '',null,t11.action_video_url),
                 if(nvl(t13.action_video_url,'') = '',null,t13.action_video_url),'') as action_video_url,
        coalesce(if(nvl(t9.action_guide_tip,'') = '',null,t9.action_guide_tip),
                 if(nvl(t10.action_guide_tip,'') = '',null,t10.action_guide_tip),
                 if(nvl(t11.action_guide_tip,'') = '',null,t11.action_guide_tip),
                 if(nvl(t13.action_guide_tip,'') = '',null,t13.action_guide_tip),'') as action_guide_tip,
        coalesce(if(nvl(t9.action_pic_url,'') = '',null,t9.action_pic_url),
                 if(nvl(t10.action_pic_url,'') = '',null,t10.action_pic_url),
                 if(nvl(t11.action_pic_url,'') = '',null,t11.action_pic_url),
                 if(nvl(t13.action_pic_url,'') = '',null,t13.action_pic_url),'') as action_pic_url,
        coalesce(if(nvl(t9.action_intent,'') = '',null,t9.action_intent),
                 if(nvl(t10.action_intent,'') = '',null,t10.action_intent),
                 if(nvl(t11.action_intent,'') = '',null,t11.action_intent),
                 if(nvl(t13.action_intent,'') = '',null,t13.action_intent),'') as action_intent,
        coalesce(if(nvl(t9.action_url,'') = '',null,t9.action_url),
                 if(nvl(t10.action_url,'') = '',null,t10.action_url),
                 if(nvl(t11.action_url,'') = '',null,t11.action_url),
                 if(nvl(t13.action_url,'') = '',null,t13.action_url),'') as action_url,
        coalesce(if(nvl(t9.action_display,'') = '',null,t9.action_display),
                 if(nvl(t10.action_display,'') = '',null,t10.action_display),
                 if(nvl(t11.action_display,'') = '',null,t11.action_display),
                 if(nvl(t13.action_display,'') = '',null,t13.action_display),'') as action_display,
        coalesce(if(nvl(t9.action_name,'') = '',null,t9.action_name),
                 if(nvl(t10.action_name,'') = '',null,t10.action_name),
                 if(nvl(t11.action_name,'') = '',null,t11.action_name),
                 if(nvl(t13.action_name,'') = '',null,t13.action_name),'') as action_name,
        coalesce(if(nvl(t9.tts_audio,'') = '',null,t9.tts_audio),
                 if(nvl(t10.tts_audio,'') = '',null,t10.tts_audio),
                 if(nvl(t11.tts_audio,'') = '',null,t11.tts_audio),
                 if(nvl(t13.tts_audio,'') = '',null,t13.tts_audio),'') as tts_audio,
        coalesce(if(nvl(t9.tts_type,'') = '',null,t9.tts_type),
                 if(nvl(t10.tts_type,'') = '',null,t10.tts_type),
                 if(nvl(t11.tts_type,'') = '',null,t11.tts_type),
                 if(nvl(t13.tts_type,'') = '',null,t13.tts_type),'') as tts_type,
        nvl(t9.k8s_svc_name,'') as asr_qa_k8s_svc_name,
        nvl(t9.k8s_env_name,'') as asr_qa_k8s_env_name,
        nvl(t9.event_time,'') as asr_qa_event_time,
        case when nvl(t9.question_id,'') != '' then 1
             else 0
            end as is_asr_qa,
        nvl(t10.k8s_svc_name,'') as reception_qa_k8s_svc_name,
        nvl(t10.k8s_env_name,'') as reception_qa_k8s_env_name,
        nvl(t10.event_time,'') as reception_qa_event_time,
        case when nvl(t10.question_id,'') != '' then 1
             else 0
            end as is_reception_qa,
        coalesce(if(nvl(t7.rcu_id,'') = '',null,t7.rcu_id),
                 if(nvl(t11.rcu_id,'') = '',null,t11.rcu_id),
                 if(nvl(t12.rcu_id,'') = '',null,t12.rcu_id),'') as rcu_id,
        nvl(t11.msg_from,'') as robot_qa_msg_from,
        nvl(t11.msg_send_name,'') as robot_qa_msg_send_name,
        nvl(t11.msg_id,'') as robot_qa_msg_id,
        nvl(t11.msg_receive_name,'') as robot_qa_msg_receive_name,
        nvl(t11.msg_type,'') as robot_qa_msg_type,
        nvl(t11.msg_dest,'') as robot_qa_msg_dest,
        nvl(t11.send_delay,-99999998) as robot_qa_send_delay,
        nvl(t11.k8s_svc_name,'') as robot_qa_k8s_svc_name,
        nvl(t11.k8s_env_name,'') as robot_qa_k8s_env_name,
        nvl(t11.event_time,'') as robot_qa_event_time,
        case when nvl(t11.question_id,'') != '' then 1
             else 0
            end as is_robot_qa,
        coalesce(if(nvl(t12.hi_account,'') = '',null,t12.hi_account),
                 if(nvl(t13.msg_send_name,'') = '',null,t13.msg_send_name),'') as hi_account,
        nvl(t12.msg,'') as hi_intelligence_msg,
        nvl(t12.msg_from,'') as hi_intelligence_msg_from,
        nvl(t12.msg_from_name,'') as hi_intelligence_msg_from_name,
        nvl(t12.msg_type,'') as hi_intelligence_msg_type,
        nvl(t12.k8s_svc_name,'') as hi_intelligence_k8s_svc_name,
        nvl(t12.k8s_env_name,'') as hi_intelligence_k8s_env_name,
        nvl(t12.event_time,'') as hi_intelligence_event_time,
        case when nvl(t12.question_id,'') != '' then 1
             else 0
            end as is_hi_intelligence,
        nvl(t13.msg_from,'') as hi_qa_msg_from,
        nvl(t13.msg_send_name,'') as hi_qa_msg_send_name,
        nvl(t13.msg_id,'') as hi_qa_msg_id,
        nvl(t13.msg_type,'') as hi_qa_msg_type,
        nvl(t13.k8s_svc_name,'') as hi_qa_k8s_svc_name,
        nvl(t13.k8s_env_name,'') as hi_qa_k8s_env_name,
        nvl(t13.event_time,'') as hi_qa_event_time,
        case when nvl(t13.question_id,'') != '' then 1
             else 0
            end as is_hi_qa,
        least(if(nvl(t2.event_time,'') = '','9999-12-31 23:59:59.999',t2.event_time),
              if(nvl(t3.event_time,'') = '','9999-12-31 23:59:59.999',t3.event_time),
              if(nvl(t4.event_time,'') = '','9999-12-31 23:59:59.999',t4.event_time),
              if(nvl(t5.event_time,'') = '','9999-12-31 23:59:59.999',t5.event_time),
              if(nvl(t6.event_time,'') = '','9999-12-31 23:59:59.999',t6.event_time),
              if(nvl(t7.event_time,'') = '','9999-12-31 23:59:59.999',t7.event_time),
              if(nvl(t8.event_time,'') = '','9999-12-31 23:59:59.999',t8.event_time),
              if(nvl(t9.event_time,'') = '','9999-12-31 23:59:59.999',t9.event_time),
              if(nvl(t10.event_time,'') = '','9999-12-31 23:59:59.999',t10.event_time),
              if(nvl(t11.event_time,'') = '','9999-12-31 23:59:59.999',t11.event_time),
              if(nvl(t12.event_time,'') = '','9999-12-31 23:59:59.999',t12.event_time),
              if(nvl(t13.event_time,'') = '','9999-12-31 23:59:59.999',t13.event_time)) as conversation_start_time,
        greatest(if(nvl(t2.event_time,'') = '','',t2.event_time),
                 if(nvl(t3.event_time,'') = '','',t3.event_time),
                 if(nvl(t4.event_time,'') = '','',t4.event_time),
                 if(nvl(t5.event_time,'') = '','',t5.event_time),
                 if(nvl(t6.event_time,'') = '','',t6.event_time),
                 if(nvl(t7.event_time,'') = '','',t7.event_time),
                 if(nvl(t8.event_time,'') = '','',t8.event_time),
                 if(nvl(t9.event_time,'') = '','',t9.event_time),
                 if(nvl(t10.event_time,'') = '','',t10.event_time),
                 if(nvl(t11.event_time,'') = '','',t11.event_time),
                 if(nvl(t12.event_time,'') = '','',t12.event_time),
                 if(nvl(t13.event_time,'') = '','',t13.event_time)) as conversation_end_time,
        coalesce(if(nvl(t2.k8s_env_name,'') = '',null,t2.k8s_env_name),
                 if(nvl(t3.k8s_env_name,'') = '',null,t3.k8s_env_name),
                 if(nvl(t4.k8s_env_name,'') = '',null,t4.k8s_env_name),
                 if(nvl(t5.k8s_env_name,'') = '',null,t5.k8s_env_name),
                 if(nvl(t6.k8s_env_name,'') = '',null,t6.k8s_env_name),
                 if(nvl(t7.k8s_env_name,'') = '',null,t7.k8s_env_name),
                 if(nvl(t8.k8s_env_name,'') = '',null,t8.k8s_env_name),
                 if(nvl(t9.k8s_env_name,'') = '',null,t9.k8s_env_name),
                 if(nvl(t10.k8s_env_name,'') = '',null,t10.k8s_env_name),
                 if(nvl(t11.k8s_env_name,'') = '',null,t11.k8s_env_name),
                 if(nvl(t12.k8s_env_name,'') = '',null,t12.k8s_env_name),
                 if(nvl(t13.k8s_env_name,'') = '',null,t13.k8s_env_name),'') as cmd_k8s_env_name,
        if(coalesce(if(nvl(t2.k8s_env_name,'') = '',null,t2.k8s_env_name),
                    if(nvl(t3.k8s_env_name,'') = '',null,t3.k8s_env_name),
                    if(nvl(t4.k8s_env_name,'') = '',null,t4.k8s_env_name),
                    if(nvl(t5.k8s_env_name,'') = '',null,t5.k8s_env_name),
                    if(nvl(t6.k8s_env_name,'') = '',null,t6.k8s_env_name),
                    if(nvl(t7.k8s_env_name,'') = '',null,t7.k8s_env_name),
                    if(nvl(t8.k8s_env_name,'') = '',null,t8.k8s_env_name),
                    if(nvl(t9.k8s_env_name,'') = '',null,t9.k8s_env_name),
                    if(nvl(t10.k8s_env_name,'') = '',null,t10.k8s_env_name),
                    if(nvl(t11.k8s_env_name,'') = '',null,t11.k8s_env_name),
                    if(nvl(t12.k8s_env_name,'') = '',null,t12.k8s_env_name),
                    if(nvl(t13.k8s_env_name,'') = '',null,t13.k8s_env_name),'') = 'bj-prod-221','bj-prod-232',
           coalesce(if(nvl(t2.k8s_env_name,'') = '',null,t2.k8s_env_name),
                    if(nvl(t3.k8s_env_name,'') = '',null,t3.k8s_env_name),
                    if(nvl(t4.k8s_env_name,'') = '',null,t4.k8s_env_name),
                    if(nvl(t5.k8s_env_name,'') = '',null,t5.k8s_env_name),
                    if(nvl(t6.k8s_env_name,'') = '',null,t6.k8s_env_name),
                    if(nvl(t7.k8s_env_name,'') = '',null,t7.k8s_env_name),
                    if(nvl(t8.k8s_env_name,'') = '',null,t8.k8s_env_name),
                    if(nvl(t9.k8s_env_name,'') = '',null,t9.k8s_env_name),
                    if(nvl(t10.k8s_env_name,'') = '',null,t10.k8s_env_name),
                    if(nvl(t11.k8s_env_name,'') = '',null,t11.k8s_env_name),
                    if(nvl(t12.k8s_env_name,'') = '',null,t12.k8s_env_name),
                    if(nvl(t13.k8s_env_name,'') = '',null,t13.k8s_env_name),'')) as join_k8s_env_name
    from union_question_id t1
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            is_noise,
            robot_account_id,
            version,
            sid,
            service_code,
            tenant_id,
            app_type,
            robot_type,
            rod_type,
            audio_record_type,
            qa_flag,
            duration,
            dialect,
            audio_sample_rate,
            asr_vendor,
            format,
            channel,
            `language`,
            sv_agent_id,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_rcu_record_i_d  where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t2 on t1.question_id = t2.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            is_noise,
            robot_account_id,
            version,
            sid,
            service_code,
            tenant_id,
            app_type,
            robot_type,
            rod_type,
            audio_record_type,
            qa_flag,
            duration,
            dialect,
            audio_sample_rate,
            asr_vendor,
            format,
            channel,
            `language`,
            vpr_id,
            question_text,
            audio_length,
            asr_vendor_delay,
            rcc_delay,
            forward_delay,
            sv_agent_id,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_asr_recognize_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t3 on t1.question_id = t3.question_id
    left join (
        select
            question_id,
            robot_id,
            robot_account_id,
            version,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            question_text,
            asr_domain,
            asr_third_total,
            asr_vendor,
            asr_start,
            asr_end,
            nlufwd,
            sv_agent_id,
            wake_status,
            wake_status_name,
            nlp_total,
            log_module,
            gap,
            vocal_total,
            last_pre_end_start,
            asrctrl_duration,
            x_b3_traceid,
            asrctrl_inner,
            caller,
            is_pre_end,
            vpr_id,
            asrctrl_robot_skill_total,
            asr_nlp_total,
            audio_size,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_asr_cmd_asr_hit_domain_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t4 on t1.question_id = t4.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            qa_flag,
            question_text,
            hi_status,
            `language`,
            latitude,
            longitude,
            send_delay,
            queue_delay,
            total_delay,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_asr_send_txt_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t5 on t1.question_id = t5.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            qa_flag,
            question_text,
            question_language,
            send_delay,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_reception_send_txt_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t6 on t1.question_id = t6.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            harix_switch_id,
            rcu_id,
            type_url,
            qa_flag,
            question_text,
            question_language,
            msg_from,
            msg_send_name,
            msg_id,
            msg_receive_name,
            msg_type,
            msg_dest,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_robot_send_txt_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t7 on t1.question_id = t7.question_id
    left join (
        select
            question_id,
            robot_id,
            robot_type,
            robot_account_id,
            sv_agent_id,
            sv_agent_name,
            algo,
            cost,
            matched_template_id,
            matched_template,
            domain_id,
            domain_name,
            intent_id,
            intent_name,
            env_info,
            before_context,
            in_context,
            out_context,
            param_info,
            parameters,
            qa_result,
            fqa_cate_id,
            user_qa_cate_id,
            question_group_id,
            sim_question_score,
            question_text,
            answer_text,
            session_id,
            qa_from,
            is_hi,
            vpr_id,
            emotion,
            is_rc,
            supplier,
            supplier_type,
            third_cost,
            third_session_id,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_nlp_cmd_nlu_recognize_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t8 on t1.question_id = t8.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            sid,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            qa_flag,
            question_text,
            question_language,
            answer_text,
            answer_language,
            confidence,
            hi_status,
            `language`,
            latitude,
            longitude,
            send_delay,
            queue_delay,
            total_delay,
            msg_from,
            qa_from,
            tts_step,
            intent_name,
            tts_emoji,
            tts_payload,
            action_duration,
            action_frame_no,
            action_play_type,
            action_video_url,
            action_guide_tip,
            action_pic_url,
            action_intent,
            action_url,
            action_display,
            action_name,
            tts_audio,
            tts_type,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_asr_send_qa_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t9 on t1.question_id = t9.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            qa_flag,
            question_text,
            question_language,
            answer_text,
            answer_language,
            tts_step,
            intent_name,
            tts_emoji,
            tts_payload,
            action_duration,
            action_frame_no,
            action_play_type,
            action_video_url,
            action_guide_tip,
            action_pic_url,
            action_intent,
            action_url,
            action_display,
            action_name,
            tts_audio,
            tts_type,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_reception_send_qa_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t10 on t1.question_id = t10.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            harix_switch_id,
            rcu_id,
            type_url,
            qa_flag,
            question_text,
            question_language,
            answer_text,
            answer_language,
            msg_from,
            msg_send_name,
            msg_id,
            msg_receive_name,
            msg_type,
            msg_dest,
            tts_step,
            intent_name,
            tts_emoji,
            tts_payload,
            action_duration,
            action_frame_no,
            action_play_type,
            action_video_url,
            action_guide_tip,
            action_pic_url,
            action_intent,
            action_url,
            action_display,
            action_name,
            tts_audio,
            tts_type,
            send_delay,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_robot_send_qa_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t11 on t1.question_id = t11.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_id,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            hi_account,
            msg,
            msg_from,
            msg_from_name,
            msg_type,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_hi_intelligence_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t12 on t1.question_id = t12.question_id
    left join (
        select
            question_id,
            robot_id,
            rcu_audio,
            robot_account_id,
            service_code,
            tenant_id,
            robot_type,
            rod_type,
            qa_flag,
            harix_switch_id,
            question_text,
            question_language,
            answer_text,
            answer_language,
            msg_from,
            msg_send_name,
            msg_id,
            msg_type,
            tts_step,
            intent_name,
            tts_emoji,
            tts_payload,
            action_duration,
            action_frame_no,
            action_play_type,
            action_video_url,
            action_guide_tip,
            action_pic_url,
            action_intent,
            action_url,
            action_display,
            action_name,
            tts_audio,
            tts_type,
            k8s_svc_name,
            k8s_env_name,
            event_time
        from cdmdwd.dwd_harix_cmd_hi_send_qa_i_d where dt >= date_sub('${s_dt_var}',2) and dt <= '${e_dt_var}'
    ) t13 on t1.question_id = t13.question_id
),
dim_audio_process as (
    select
        t1.question_id,
        nvl(t3.customer_id,'') as customer_id,
        nvl(t3.customer_name,'') as customer_name,
        nvl(t3.pid,'') as pid,
        nvl(t3.`level`,'') as level,
        nvl(t3.region,'') as customer_region,
        nvl(t3.address,'') as customer_address,
        nvl(t3.website,'') as website,
        nvl(t3.industry_id,'') as customer_industry_id,
        nvl(t12.industry_name,'') as customer_industry_name,
        nvl(t3.nature_code,'') as nature_code,
        nvl(t3.nature_name,'') as nature_name,
        nvl(t3.credit_code,'') as credit_code,
        nvl(t3.credit_name,'') as credit_name,
        nvl(t3.source_code,'') as source_code,
        nvl(t3.source_name,'') as source_name,
        nvl(t3.scale_code,'') as scale_code,
        nvl(t3.scale_name,'') as scale_name,
        nvl(t3.status_code,'') as status_code,
        nvl(t3.status_name,'') as status_name,
        nvl(t3.contact_code,'') as contact_code,
        nvl(t3.contact_name,'') as contact_name,
        nvl(t3.purchase_code,'') as purchase_code,
        nvl(t3.purchase_name,'') as purchase_name,
        nvl(t3.employment_code,'') as employment_code,
        nvl(t3.employment_name,'') as employment_name,
        nvl(t3.settlement_code,'') as settlement_code,
        nvl(t3.settlement_name,'') as settlement_name,
        cast(nvl(t3.employer_num,-99999998) as int) as employer_num,
        nvl(t3.category_code,'') as category_code,
        nvl(t3.category_name,'') as category_name,
        nvl(t3.create_time,'') as customer_create_time,

        t1.tenant_id,
        nvl(t2.tenant_name,'') as tenant_name,
        nvl(t2.tenant_type,'') as tenant_type,
        nvl(t2.industry_id,'') as tenant_industry_id,
        nvl(t13.industry_name,'') as tenant_industry_name,
        nvl(t2.sub_sys,'') as sub_sys,
        nvl(t2.time_zone,'') as time_zone,
        nvl(t2.net_env_id,'') as net_env_id,
        nvl(t2.mcs_area,'') as mcs_area,
        cast(nvl(t2.device_num,-99999998) as int) as device_num,
        nvl(t2.region,'') as tenant_region,
        nvl(t2.address,'') as tenant_address,
        nvl(t2.contact,'') as contact,
        nvl(t2.phone,'') as tenant_phone,
        nvl(t2.telephone,'') as telephone,
        nvl(t2.seller,'') as seller,
        nvl(t2.email,'') as tenant_email,
        nvl(t2.status,-99999998) as tenant_status,
        nvl(t2.status_name,'未知') as tenant_status_name,
        nvl(t2.charge_time,'') as charge_time,
        nvl(t2.expired_time,'') as expired_time,
        nvl(t2.logo,'') as logo,
        nvl(t2.description,'') as tenant_description,
        nvl(t2.brand,'') as brand,
        cast(nvl(t2.is_need_vpn,-99999998) as int) as is_need_vpn,
        nvl(t2.create_time,'') as tenant_create_time,

        t1.robot_id,
        nvl(t4.robot_name,'') as robot_name,
        nvl(t4.robot_type_id,'') as robot_type_id,
        nvl(t4.robot_type_inner_name,'') as robot_type_inner_name,
        nvl(t4.robot_type_name,'') as robot_type_name,
        nvl(t4.asset_code,'') as asset_code,
        nvl(t4.asset_type,'') as asset_type,
        nvl(t4.product_type_code,'') as product_type_code,
        nvl(t4.product_type_code_name,'') as product_type_code_name,
        nvl(t4.product_id,'') as product_id,
        nvl(t4.product_id_name,'') as product_id_name,
        nvl(t4.assets_status,-99999998) as assets_status,
        nvl(t4.assets_status_name,'未知') as assets_status_name,
        nvl(t4.status,-99999998) as robot_status,
        nvl(t4.status_name,'未知') as robot_status_name,
        nvl(t4.robot_manufacturer_id,'') as robot_manufacturer_id,
        nvl(t4.robot_manufacturer_name,'') as robot_manufacturer_name,
        nvl(t4.model,'') as robot_model,
        nvl(t4.os,'') as robot_os,
        nvl(t4.version_code,'') as robot_version_code,
        nvl(t4.software_version,'') as software_version,
        nvl(t4.hardware_version,'') as hardware_version,
        nvl(t4.head_url,'') as head_url,
        nvl(t4.regist_time,'') as robot_regist_time,
        cast(nvl(t4.bind_status,-99999998) as int) as bind_status,
        nvl(t4.bind_status_name,'未知') as bind_status_name,
        cast(nvl(t4.is_hi_service,-99999998) as int) as is_hi_service,
        cast(nvl(t4.is_privacy_enhance,-99999998) as int) as is_privacy_enhance,
        nvl(t4.remind_policy_id,'') as remind_policy_id,
        nvl(t4.sku,'') as sku,
        nvl(t4.quality_date,'') as quality_date,
        nvl(t4.customer_quality_date,'') as customer_quality_date,
        nvl(t4.out_type_state,-99999998) as out_type_state,
        nvl(t4.out_type_state_name,'未知') as out_type_state_name,
        nvl(t4.product_date,'') as product_date,
        nvl(t4.in_stock_date,'') as in_stock_date,
        nvl(t4.out_stock_date,'') as out_stock_date,
        nvl(t4.in_stock_staff_id,'') as in_stock_staff_id,
        nvl(t4.in_stock_staff_name,'') as in_stock_staff_name,
        nvl(t4.out_stock_staff_id,'') as out_stock_staff_id,
        nvl(t4.out_stock_staff_name,'') as out_stock_staff_name,
        nvl(t4.note,'') as robot_note,
        nvl(t4.description,'') as description,
        nvl(t4.create_time,'') as robot_create_time,

        t1.rcu_id,
        nvl(t5.rcu_name,'') as rcu_name,
        nvl(t5.imei,'') as imei,
        nvl(t5.did,'') as did,
        nvl(t5.did_credential_id,'') as did_credential_id,
        nvl(t5.rcu_manufacturer_name,'') as rcu_manufacturer_name,
        nvl(t5.model,'') as rcu_model,
        nvl(t5.os,'') as rcu_os,
        nvl(t5.version_code,'') as rcu_version_code,
        nvl(t5.status,-99999998) as rcu_status,
        nvl(t5.status_name,'未知') as rcu_status_name,
        nvl(t5.cpu,'') as cpu,
        nvl(t5.ram,'') as ram,
        nvl(t5.rom_capacity,'') as rom_capacity,
        nvl(t5.rom_available_capacity,'') as rom_available_capacity,
        nvl(t5.sd_capacity,'') as sd_capacity,
        nvl(t5.sd_available_capacity,'') as sd_available_capacity,
        nvl(t5.camera,'') as camera,
        nvl(t5.wifi_mac,'') as wifi_mac,
        nvl(t5.bluetooth_mac,'') as bluetooth_mac,
        nvl(t5.regist_time,'') as rcu_regist_time,
        nvl(t5.activate_time,'') as activate_time,
        nvl(t5.deactivate_time,'') as deactivate_time,
        nvl(t5.description,'') as rcu_description,
        nvl(t5.create_time,'') as rcu_create_time,

        t1.robot_account_id,
        nvl(t6.robot_account_name,'') as robot_account_name,
        nvl(t6.email,'') as robot_account_email,
        nvl(t6.phone,'') as robot_account_phone,
        nvl(t6.status,-99999998) as robot_account_status,
        nvl(t6.status_name,'未知') as robot_account_status_name,
        cast(nvl(t6.privacy_type,-99999998) as int) as privacy_type,
        nvl(t6.privacy_type_name,'') as privacy_type_name,
        cast(nvl(t6.is_hi_service,-99999998) as int) as robot_account_is_hi_service,
        cast(nvl(t6.is_privacy_enhance,-99999998) as int) as robot_account_is_privacy_enhance,
        cast(nvl(t6.is_auto_takeover,-99999998) as int) as is_auto_takeover,
        nvl(t6.app_id,'') as app_id,
        nvl(t6.video_mode,'') as video_mode,
        nvl(t6.phone_number_prefix,'') as phone_number_prefix,
        nvl(t6.operator_id,'') as roc_operator_id,
        nvl(t6.ross_credential_id,'') as ross_credential_id,
        nvl(t6.create_time,'') as robot_account_create_time,

        t1.fqa_cate_id,
        nvl(t7.pid,'') as fqa_pid,
        nvl(t7.cate_id_path,'') as fqa_cate_id_path,
        nvl(t7.cate_name_path,'') as fqa_cate_name_path,
        nvl(t7.cate_name,'') as fqa_cate_name,
        nvl(t7.level,-99999998) as fqa_level,
        nvl(t7.is_work,-99999998) as fqa_is_work,
        nvl(t7.is_work_name,'未知') as fqa_is_work_name,
        nvl(t7.push_action_name,'') as fqa_push_action_name,
        nvl(t7.is_need_push,-99999998) as fqa_is_need_push,
        nvl(t7.is_del,-99999998) as fqa_is_del,
        nvl(t7.last_seq_id,'') as fqa_last_seq_id,
        nvl(t7.audit_name,'') as fqa_audit_name,
        nvl(t7.sv_msg,'') as fqa_sv_msg,
        nvl(t7.source,'') as fqa_source,
        nvl(t7.create_time,'') as fqa_create_time,

        t1.user_qa_cate_id,
        nvl(t8.pid,'') as user_qa_pid,
        nvl(t8.cate_id_path,'') as user_qa_cate_id_path,
        nvl(t8.cate_name_path,'') as user_qa_cate_name_path,
        nvl(t8.cate_name,'') as user_qa_cate_name,
        nvl(t8.level,-99999998) as user_qa_level,
        nvl(t8.is_work,-99999998) as user_qa_is_work,
        nvl(t8.is_work_name,'未知') as user_qa_is_work_name,
        nvl(t8.audit_name,'') as user_qa_audit_name,
        nvl(t8.agent_id,'') as user_qa_agent_id,
        nvl(t8.source,'') as user_qa_source,
        nvl(t8.create_time,'') as user_qa_create_time,

        t1.hi_account,
        nvl(t9.hi_name,'') as hi_name,
        nvl(t9.email,'') as hi_email,
        nvl(t9.phone,'') as hi_phone,
        cast(nvl(t9.load_type,-99999998) as int) as load_type,
        nvl(t9.load_type_name,'') as load_type_name,
        nvl(t9.operator_id,'') as hi_operator_id,
        nvl(t9.hi_group,'') as hi_group,
        nvl(t9.create_time,'') as hi_create_time,

        cast(t1.intent_id as string) as intent_id,
        case when nvl(t1.intent_name,'') != '' then t1.intent_name
             else nvl(t10.intent_name,'')
        end as intent_name,
        cast(nvl(t10.agent_id,-99999998) as int) as nlp_agent_id,
        nvl(t10.input_context,'') as input_context,
        nvl(t10.output_context,'') as output_context,
        nvl(t10.voice_pad,'') as voice_pad,
        nvl(t10.prompt,'') as prompt,
        nvl(t10.action,'') as `action`,
        nvl(t10.df_intent_id,'') as df_intent_id,
        cast(nvl(t10.lua_enabled,-99999998) as int) as is_lua_enabled,
        nvl(t10.reply,-99999998) as reply,
        nvl(t10.create_time,'') as intent_create_time,

        cast(t1.domain_id as string) domain_id,
        case when nvl(t1.domain_name,'') != '' then t1.domain_name
             else nvl(t11.domain_name,'')
        end as domain_name,
        nvl(t11.domain_info,'') as domain_info,
        nvl(t11.domain_type,'') as domain_type,
        nvl(t11.url,'') as domain_url,
        nvl(t11.call_service,'') as call_service,
        cast(nvl(t11.is_release,0) as int) as is_release,
        cast(nvl(t11.is_closed_recg,0) as int) as is_closed_recg,
        nvl(t11.closed_hit,'') as closed_hit,
        cast(nvl(t11.keyword,1) as int) as keyword,
        nvl(t11.domain_switch_hit,'') as domain_switch_hit,
        nvl(t11.create_time,'') as domain_create_time,

        t1.rcu_audio,
        t1.is_noise,
        t1.service_code,
        t1.app_type,
        t1.robot_type,
        t1.audio_record_type,
        t1.qa_flag,
        cast(t1.duration as int) as duration,
        t1.dialect,
        t1.audio_sample_rate,
        t1.asr_vendor,
        t1.format,
        t1.channel,

        t1.rcu_record_k8s_svc_name,
        t1.rcu_record_k8s_env_name,
        t1.rcu_record_event_time,
        t1.is_rcu_record,
        t1.vpr_id,
        t1.question_text,
        t1.question_language,
        t1.audio_length,
        t1.asr_vendor_delay,
        t1.rcc_delay,
        t1.forward_delay,
        t1.asr_recognize_k8s_svc_name,
        t1.asr_recognize_k8s_env_name,
        t1.asr_recognize_event_time,
        t1.is_asr_recognize,
        t1.asr_domain,
        t1.asr_third_total,
        t1.asr_start,
        t1.asr_end,
        t1.nlufwd,
        t1.wake_status,
        t1.wake_status_name,
        t1.nlp_total,
        t1.gap,
        t1.vocal_total,
        t1.last_pre_end_start,
        t1.asrctrl_duration,
        t1.x_b3_traceid,
        t1.asrctrl_inner,
        t1.caller,
        t1.is_pre_end,
        t1.asrctrl_robot_skill_total,
        t1.asr_nlp_total,
        t1.audio_size,
        t1.asr_domain_k8s_svc_name,
        t1.asr_domain_k8s_env_name,
        t1.asr_domain_event_time,
        t1.is_asr_domain,
        t1.is_hi_online,
        t1.latitude,
        t1.longitude,
        t1.txt_send_delay,
        t1.txt_queue_delay,
        t1.txt_total_delay,
        t1.asr_text_k8s_svc_name,
        t1.asr_text_k8s_env_name,
        t1.asr_text_event_time,
        t1.is_asr_text,
        t1.reception_text_k8s_svc_name,
        t1.reception_text_k8s_env_name,
        t1.reception_text_event_time,
        t1.is_reception_text,
        t1.harix_switch_id,
        t1.type_url,
        t1.robot_text_msg_from,
        t1.robot_text_msg_send_name,
        t1.robot_text_msg_id,
        t1.robot_text_msg_receive_name,
        t1.robot_text_msg_type,
        t1.robot_text_msg_dest,
        t1.robot_text_k8s_svc_name,
        t1.robot_text_k8s_env_name,
        t1.robot_text_event_time,
        t1.is_robot_text,

        t1.sv_agent_id,
        t1.sv_agent_name,
        t1.algo,
        t1.cost,
        t1.matched_template,
        t1.env_info,
        t1.before_context,
        t1.in_context,
        t1.out_context,
        t1.param_info,
        t1.parameters,
        t1.qa_result,
        t1.question_group_id,
        t1.sim_question_score,
        t1.answer_text,
        t1.answer_language,
        t1.sv_answer_text,
        t1.session_id,
        t1.qa_from,
        t1.supplier,
        t1.supplier_type,
        t1.third_cost,
        t1.third_session_id,
        t1.nlu_k8s_svc_name,
        t1.nlu_k8s_env_name,
        t1.nlu_event_time,
        t1.is_nlp,
        t1.confidence,
        t1.qa_send_delay,
        t1.qa_queue_delay,
        t1.qa_total_delay,
        t1.asr_qa_msg_from,
        t1.tts_step,
        t1.tts_emoji,
        t1.tts_payload,
        t1.action_duration,
        t1.action_frame_no,
        t1.action_play_type,
        t1.action_video_url,
        t1.action_guide_tip,
        t1.action_pic_url,
        t1.action_intent,
        t1.action_url,
        t1.action_display,
        t1.action_name,
        t1.tts_audio,
        t1.tts_type,
        t1.asr_qa_k8s_svc_name,
        t1.asr_qa_k8s_env_name,
        t1.asr_qa_event_time,
        t1.is_asr_qa,
        t1.reception_qa_k8s_svc_name,
        t1.reception_qa_k8s_env_name,
        t1.reception_qa_event_time,
        t1.is_reception_qa,

        t1.robot_qa_msg_from,
        t1.robot_qa_msg_send_name,
        t1.robot_qa_msg_id,
        t1.robot_qa_msg_receive_name,
        t1.robot_qa_msg_type,
        t1.robot_qa_msg_dest,
        t1.robot_qa_send_delay,
        t1.robot_qa_k8s_svc_name,
        t1.robot_qa_k8s_env_name,
        t1.robot_qa_event_time,
        t1.is_robot_qa,

        t1.hi_intelligence_msg,
        t1.hi_intelligence_msg_from,
        t1.hi_intelligence_msg_from_name,
        t1.hi_intelligence_msg_type,
        t1.hi_intelligence_k8s_svc_name,
        t1.hi_intelligence_k8s_env_name,
        t1.hi_intelligence_event_time,
        t1.is_hi_intelligence,
        t1.hi_qa_msg_from,
        t1.hi_qa_msg_send_name,
        t1.hi_qa_msg_id,
        t1.hi_qa_msg_type,
        t1.hi_qa_k8s_svc_name,
        t1.hi_qa_k8s_env_name,
        t1.hi_qa_event_time,
        t1.is_hi_qa,
        t1.conversation_start_time,
        t1.conversation_end_time,
        t1.cmd_k8s_env_name,
        substring(conversation_start_time,0,10) as dt
        -- 用于过滤维度不为空,以及判断conversation_start为start end 时间的数量,假设前提所有不为空的维度都能关联上满足条件的维度信息
--         if(nvl(t1.tenant_id,'') != '',1,0) + if(nvl(t2.customer_id,'') != '',1,0) + if(nvl(t1.robot_id,'') != '',1,0) + if(nvl(t1.rcu_id,'') != '',1,0) + if(nvl(t1.robot_account_id,'') != '',1,0) + if(nvl(t1.fqa_cate_id,'') != '',1,0) + if(nvl(t1.user_qa_cate_id,'') != '',1,0) as id_cnt,
--         if(t1.conversation_start_time between t2.start_time and t2.end_time,1,0) + if(t1.conversation_start_time between t3.start_time and t3.end_time,1,0) + if(t1.conversation_start_time between t4.start_time and t4.end_time,1,0) + if(t1.conversation_start_time between t5.start_time and t5.end_time,1,0) + if(t1.conversation_start_time between t6.start_time and t6.end_time,1,0) + if(t1.conversation_start_time between t7.start_time and t7.end_time,1,0) + if(t1.conversation_start_time between t8.start_time and t8.end_time,1,0) as flag_cnt
    from audio_process_tmp t1
    left join (
        select
            tenant_id,
            tenant_name,
            tenant_type,
            customer_id,
            industry_id,
            sub_sys,
            time_zone,
            net_env_id,
            mcs_area,
            device_num,
            region,
            address,
            contact,
            phone,
            telephone,
            seller,
            email,
            boss_status as status,
            boss_status_name as status_name,
            charge_time,
            expired_time,
            logo,
            description,
            brand,
            is_need_vpn,
            start_time,
            end_time,
            k8s_env_name,
            create_time
        from cdmdim.dim_umd_tenant_sh_d where dt = date_sub(current_date,1)
    ) t2 on t1.tenant_id = t2.tenant_id
    left join (
        select
            customer_id,
            customer_name,
            pid,
            level,
            region,
            address,
            website,
            industry_id,
            nature_code,
            nature_name,
            credit_code,
            credit_name,
            source_code,
            source_name,
            scale_code,
            scale_name,
            status_code,
            status_name,
            contact_code,
            contact_name,
            purchase_code,
            purchase_name,
            employment_code,
            employment_name,
            settlement_code,
            settlement_name,
            employer_num,
            category_code,
            category_name,
            create_time,
            update_time,
            start_time,
            end_time
        from cdmdim.dim_umd_customer_sh_d where dt = date_sub(current_date,1)
    ) t3 on t2.customer_id = t3.customer_id
    left join (
        select
            robot_id,
            robot_name,
            robot_type_id,
            robot_type_inner_name,
            robot_type_name,
            asset_code,
            asset_type,
            product_type_code,
            product_type_code_name,
            product_id,
            product_id_name,
            assets_status,
            assets_status_name,
            status,
            status_name,
            robot_manufacturer_id,
            robot_manufacturer_name,
            model,
            os,
            version_code,
            software_version,
            hardware_version,
            head_url,
            regist_time,
            bind_status,
            bind_status_name,
            is_hi_service,
            is_privacy_enhance,
            remind_policy_id,
            sku,
            quality_date,
            customer_quality_date,
            out_type_state,
            out_type_state_name,
            product_date,
            in_stock_date,
            out_stock_date,
            in_stock_staff_id,
            in_stock_staff_name,
            out_stock_staff_id,
            out_stock_staff_name,
            note,
            description,
            start_time,
            end_time,
            k8s_env_name,
            create_time,
            update_time
        from cdmdim.dim_pmd_robot_sh_d where dt = date_sub(current_date,1)
    ) t4 on t1.robot_id = t4.robot_id
    left join (
        select
            rcu_id,
            rcu_name,
            imei,
            did,
            did_credential_id,
            model,
            os,
            version_code,
            status,
            status_name,
            rcu_manufacturer_name,
            cpu,
            ram,
            rom_capacity,
            rom_available_capacity,
            sd_capacity,
            sd_available_capacity,
            camera,
            wifi_mac,
            bluetooth_mac,
            regist_time,
            activate_time,
            deactivate_time,
            description,
            start_time,
            end_time,
            k8s_env_name,
            create_time ,
            update_time
        from cdmdim.dim_pmd_rcu_sh_d where dt = date_sub(current_date,1)
    ) t5 on t1.rcu_id = t5.rcu_id
    left join (
        select
            robot_account_id,
            robot_account_name,
            email,
            phone,
            status,
            status_name,
            privacy_type,
            privacy_type_name,
            is_hi_service,
            is_privacy_enhance,
            is_auto_takeover,
            app_id,
            video_mode,
            phone_number_prefix,
            tenant_id,
            operator_id,
            ross_credential_id,
            start_time,
            end_time,
            k8s_env_name,
            create_time,
            update_time
        from cdmdim.dim_umd_robot_account_sh_d where dt = date_sub(current_date,1)
    ) t6 on t1.robot_account_id = t6.robot_account_id and t1.tenant_id = t6.tenant_id and t1.join_k8s_env_name = t6.k8s_env_name
    left join (
        select
            fqa_cate_id,
            pid,
            cate_name,
            level,
            is_work,
            is_work_name,
            create_time,
            update_time,
            push_action_name,
            is_need_push,
            is_del,
            last_seq_id,
            is_syn_status,
            audit_name,
            sv_msg,
            source,
            k8s_env_name,
            start_time,
            end_time,
            cate_name_path,
            cate_id_path
        from cdmdim.dim_svo_fqa_cate_sh_d where dt = date_sub(current_date,1)
    ) t7 on t1.fqa_cate_id = t7.fqa_cate_id and t1.join_k8s_env_name = t7.k8s_env_name
    left join (
        select
            user_qa_cate_id,
            pid,
            cate_name,
            level,
            is_work,
            is_work_name,
            create_time,
            update_time,
            audit_name,
            agent_id,
            source,
            k8s_env_name,
            start_time,
            end_time,
            cate_name_path,
            cate_id_path
        from cdmdim.dim_svo_user_qa_cate_sh_d where dt = date_sub(current_date ,1)
    ) t8 on t1.user_qa_cate_id = t8.user_qa_cate_id and t1.join_k8s_env_name = t8.k8s_env_name
    left join cdmdim.dim_cmd_hi_a_d t9 on t1.hi_account = t9.hi_account and t1.join_k8s_env_name = t9.k8s_env_name
    left join cdmdim.dim_cmd_intent_a_d t10 on t1.intent_id = t10.intent_id and t1.join_k8s_env_name = t10.k8s_env_name
    left join cdmdim.dim_cmd_domain_a_d t11 on t1.domain_id = t11.domain_id and t1.join_k8s_env_name = t11.k8s_env_name
    left join cdmdim.dim_umd_industry_a_d t12 on t3.industry_id = t12.industry_id
    left join cdmdim.dim_umd_industry_a_d t13 on t2.industry_id = t13.industry_id
    where (t2.start_time is null or t1.conversation_start_time between t2.start_time and t2.end_time)
      and (t3.start_time is null or t1.conversation_start_time between t3.start_time and t3.end_time)
      and (t4.start_time is null or t1.conversation_start_time between t4.start_time and t4.end_time)
      and (t5.start_time is null or t1.conversation_start_time between t5.start_time and t5.end_time)
      and (t6.start_time is null or t1.conversation_start_time between t6.start_time and t6.end_time)
      and (t7.start_time is null or t1.conversation_start_time between t7.start_time and t7.end_time)
      and (t8.start_time is null or t1.conversation_start_time between t8.start_time and t8.end_time)
)
insert overwrite table cdmdwm.dwm_cmd_audio_process_i_d partition(dt)
    select
        question_id,
        customer_id as customer__customer_id,
        customer_name as customer__customer_name,
        pid as customer__pid,
        level as customer__level,
        customer_region as customer__region,
        customer_address as customer__address,
        website as customer__website,
        customer_industry_id as customer__industry_id,
        customer_industry_name as customer__industry_name,
        nature_code as customer__nature_code,
        nature_name as customer__nature_name,
        credit_code as customer__credit_code,
        credit_name as customer__credit_name,
        source_code as customer__source_code,
        source_name as customer__source_name,
        scale_code as customer__scale_code,
        scale_name as customer__scale_name,
        status_code as customer__status_code,
        status_name as customer__status_name,
        contact_code as customer__contact_code,
        contact_name as customer__contact_name,
        purchase_code as customer__purchase_code,
        purchase_name as customer__purchase_name,
        employment_code as customer__employment_code,
        employment_name as customer__employment_name,
        settlement_code as customer__settlement_code,
        settlement_name as customer__settlement_name,
        employer_num as customer__employer_num,
        category_code as customer__category_code,
        category_name as customer__category_name,
        customer_create_time as customer__create_time,

        tenant_id as tenant__tenant_id,
        tenant_name as tenant__tenant_name,
        tenant_type as tenant__tenant_type,
        tenant_industry_id as tenant__industry_id,
        tenant_industry_name as tenant__industry_name,
        sub_sys as tenant__sub_sys,
        time_zone as tenant__time_zone,
        net_env_id as tenant__net_env_id,
        mcs_area as tenant__mcs_area,
        device_num as tenant__device_num,
        tenant_region as tenant__region,
        tenant_address as tenant__address,
        contact as tenant__contact,
        tenant_phone as tenant__phone,
        telephone as tenant__telephone,
        seller as tenant__seller,
        tenant_email as tenant__email,
        tenant_status as tenant__status,
        tenant_status_name as tenant__status_name,
        charge_time as tenant__charge_time,
        expired_time as tenant__expired_time,
        logo as tenant__logo,
        tenant_description as tenant__description,
        brand as tenant__brand,
        is_need_vpn as tenant__is_need_vpn,
        tenant_create_time as tenant__create_time,

        robot_id as robot__robot_id,
        robot_name as robot__robot_name,
        robot_type_id as robot__robot_type_id,
        robot_type_inner_name as robot__robot_type_inner_name,
        robot_type_name as robot__robot_type_name,
        asset_code as robot__asset_code,
        asset_type as robot__asset_type,
        product_type_code as robot__product_type_code,
        product_type_code_name as robot__product_type_code_name,
        product_id as robot__product_id,
        product_id_name as robot__product_id_name,
        assets_status as robot__assets_status,
        assets_status_name as robot__assets_status_name,
        robot_status as robot__status,
        robot_status_name as robot__status_name,
        robot_manufacturer_id as robot__robot_manufacturer_id,
        robot_manufacturer_name as robot__robot_manufacturer_name,
        robot_model as robot__model,
        robot_os as robot__os,
        robot_version_code as robot__version_code,
        software_version as robot__software_version,
        hardware_version as robot__hardware_version,
        head_url as robot__head_url,
        robot_regist_time as robot__regist_time,
        bind_status as robot__bind_status,
        bind_status_name as robot__bind_status_name,
        is_hi_service as robot__is_hi_service,
        is_privacy_enhance as robot__is_privacy_enhance,
        remind_policy_id as robot__remind_policy_id,
        sku as robot__sku,
        quality_date as robot__quality_date,
        customer_quality_date as robot__customer_quality_date,
        out_type_state as robot__out_type_state,
        out_type_state_name as robot__out_type_state_name,
        product_date as robot__product_date,
        in_stock_date as robot__in_stock_date,
        out_stock_date as robot__out_stock_date,
        in_stock_staff_id as robot__in_stock_staff_id,
        in_stock_staff_name as robot__in_stock_staff_name,
        out_stock_staff_id as robot__out_stock_staff_id,
        out_stock_staff_name as robot__out_stock_staff_name,
        robot_note as robot__robot_note,
        description as robot__description,
        robot_create_time as robot__create_time,

        rcu_id as rcu__rcu_id,
        rcu_name as rcu__rcu_name,
        imei as rcu__imei,
        did as rcu__did,
        did_credential_id as rcu__did_credential_id,
        rcu_manufacturer_name as rcu__rcu_manufacturer_name,
        rcu_model as rcu__model,
        rcu_os as rcu__os,
        rcu_version_code as rcu__version_code,
        rcu_status as rcu__status,
        rcu_status_name as rcu__status_name,
        cpu as rcu__cpu,
        ram as rcu__ram,
        rom_capacity as rcu__rom_capacity,
        rom_available_capacity as rcu__rom_available_capacity,
        sd_capacity as rcu__sd_capacity,
        sd_available_capacity as rcu__sd_available_capacity,
        camera as rcu__camera,
        wifi_mac as rcu__wifi_mac,
        bluetooth_mac as rcu__bluetooth_mac,
        rcu_regist_time as rcu__regist_time,
        activate_time as rcu__activate_time,
        deactivate_time as rcu__deactivate_time,
        rcu_description as rcu__description,
        rcu_create_time as rcu__create_time,

        robot_account_id as robot_account__robot_account_id,
        robot_account_name as robot_account__robot_account_name,
        robot_account_email as robot_account__email,
        robot_account_phone as robot_account__phone,
        robot_account_status as robot_account__status,
        robot_account_status_name as robot_account__status_name,
        privacy_type as robot_account__privacy_type,
        privacy_type_name as robot_account__privacy_type_name,
        robot_account_is_hi_service as robot_account__is_hi_service,
        robot_account_is_privacy_enhance as robot_account__is_privacy_enhance,
        is_auto_takeover as robot_account__is_auto_takeover,
        app_id as robot_account__app_id,
        video_mode as robot_account__video_mode,
        phone_number_prefix as robot_account__phone_number_prefix,
        roc_operator_id as robot_account__operator_id,
        ross_credential_id as robot_account__ross_credential_id,
        robot_account_create_time as robot_account__create_time,

        hi_account as hi__hi_account,
        hi_name as hi__hi_name,
        hi_email as hi__hi_email,
        hi_phone as hi__hi_phone,
        load_type as hi__load_type,
        load_type_name as hi__load_type_name,
        hi_operator_id as hi__operator_id,
        hi_group as hi__hi_group,
        hi_create_time as hi__create_time,

        intent_id as intent__intent_id,
        intent_name as intent__intent_name,
        nlp_agent_id as intent__nlp_agent_id,
        input_context as intent__input_context,
        output_context as intent__output_context,
        voice_pad as intent__voice_pad,
        prompt as intent__prompt,
        `action` as intent__action,
        df_intent_id as intent__df_intent_id,
        is_lua_enabled as intent__is_lua_enabled,
        reply as intent__reply,
        intent_create_time as intent__create_time,

        domain_id as domain__domain_id,
        domain_name as domain__domain_name,
        domain_info as domain__domain_info,
        domain_type as domain__domain_type,
        domain_url as domain__domain_url,
        call_service as domain__call_service,
        is_release as domain__is_release,
        is_closed_recg as domain__is_closed_recg,
        closed_hit as domain__closed_hit,
        keyword as domain__keyword,
        domain_switch_hit as domain__domain_switch_hit,
        domain_create_time as domain__create_time,

        fqa_cate_id as fqa_cate__fqa_cate_id,
        fqa_pid as fqa_cate__pid,
        fqa_cate_id_path as fqa_cate__cate_id_path,
        fqa_cate_name_path as fqa_cate__cate_name_path,
        fqa_cate_name as fqa_cate__cate_name,
        fqa_level as fqa_cate__level,
        fqa_is_work as fqa_cate__is_work,
        fqa_is_work_name as fqa_cate__is_work_name,
        fqa_push_action_name as fqa_cate__push_action_name,
        fqa_is_need_push as fqa_cate__is_need_push,
        fqa_is_del as fqa_cate__is_del,
        fqa_last_seq_id as fqa_cate__last_seq_id,
        fqa_audit_name as fqa_cate__audit_name,
        fqa_sv_msg as fqa_cate__sv_msg,
        fqa_source as fqa_cate__source,
        fqa_create_time as fqa_cate__create_time,

        user_qa_cate_id as user_qa_cate__user_qa_cate_id,
        user_qa_pid as user_qa_cate__pid,
        user_qa_cate_id_path as user_qa_cate__cate_id_path,
        user_qa_cate_name_path as user_qa_cate__cate_name_path,
        user_qa_cate_name as user_qa_cate__cate_name,
        user_qa_level as user_qa_cate__level,
        user_qa_is_work as user_qa_cate__is_work,
        user_qa_is_work_name as user_qa_cate__is_work_name,
        user_qa_audit_name as user_qa_cate__audit_name,
        user_qa_agent_id as user_qa_cate__agent_id,
        user_qa_source as user_qa_cate__source,
        user_qa_create_time as user_qa_cate__create_time,

        rcu_audio,
        is_noise,
        service_code,
        app_type,
        robot_type,
        audio_record_type,
        qa_flag,
        duration,
        dialect,
        audio_sample_rate,
        asr_vendor,
        format,
        channel,

        rcu_record_k8s_svc_name,
        rcu_record_k8s_env_name,
        rcu_record_event_time,
        is_rcu_record,
        vpr_id,
        question_text,
        question_language,
        audio_length,
        asr_vendor_delay,
        rcc_delay,
        forward_delay,
        asr_recognize_k8s_svc_name,
        asr_recognize_k8s_env_name,
        asr_recognize_event_time,
        is_asr_recognize,
        asr_domain,
        asr_third_total,
        asr_start,
        asr_end,
        nlufwd,
        wake_status,
        wake_status_name,
        nlp_total,
        gap,
        vocal_total,
        last_pre_end_start,
        asrctrl_duration,
        x_b3_traceid,
        asrctrl_inner,
        caller,
        is_pre_end,
        asrctrl_robot_skill_total,
        asr_nlp_total,
        audio_size,
        asr_domain_k8s_svc_name,
        asr_domain_k8s_env_name,
        asr_domain_event_time,
        is_asr_domain,
        is_hi_online,
        latitude,
        longitude,
        txt_send_delay,
        txt_queue_delay,
        txt_total_delay,
        asr_text_k8s_svc_name,
        asr_text_k8s_env_name,
        asr_text_event_time,
        is_asr_text,
        reception_text_k8s_svc_name,
        reception_text_k8s_env_name,
        reception_text_event_time,
        is_reception_text,
        harix_switch_id,
        type_url,
        robot_text_msg_from,
        robot_text_msg_send_name,
        robot_text_msg_id,
        robot_text_msg_receive_name,
        robot_text_msg_type,
        robot_text_msg_dest,
        robot_text_k8s_svc_name,
        robot_text_k8s_env_name,
        robot_text_event_time,
        is_robot_text,

        sv_agent_id,
        sv_agent_name,
        algo,
        cost,
        matched_template,
        env_info,
        before_context,
        in_context,
        out_context,
        param_info,
        parameters,
        qa_result,
        question_group_id,
        sim_question_score,
        answer_text,
        answer_language,
        sv_answer_text,
        session_id,
        qa_from,
        supplier,
        supplier_type,
        third_cost,
        third_session_id,
        nlu_k8s_svc_name,
        nlu_k8s_env_name,
        nlu_event_time,
        is_nlp,
        confidence,
        qa_send_delay,
        qa_queue_delay,
        qa_total_delay,
        asr_qa_msg_from,
        tts_step,
        tts_emoji,
        tts_payload,
        action_duration,
        action_frame_no,
        action_play_type,
        action_video_url,
        action_guide_tip,
        action_pic_url,
        action_intent,
        action_url,
        action_display,
        action_name,
        tts_audio,
        tts_type,
        asr_qa_k8s_svc_name,
        asr_qa_k8s_env_name,
        asr_qa_event_time,
        is_asr_qa,
        reception_qa_k8s_svc_name,
        reception_qa_k8s_env_name,
        reception_qa_event_time,
        is_reception_qa,

        robot_qa_msg_from,
        robot_qa_msg_send_name,
        robot_qa_msg_id,
        robot_qa_msg_receive_name,
        robot_qa_msg_type,
        robot_qa_msg_dest,
        robot_qa_send_delay,
        robot_qa_k8s_svc_name,
        robot_qa_k8s_env_name,
        robot_qa_event_time,
        is_robot_qa,

        hi_intelligence_msg,
        hi_intelligence_msg_from,
        hi_intelligence_msg_from_name,
        hi_intelligence_msg_type,
        hi_intelligence_k8s_svc_name,
        hi_intelligence_k8s_env_name,
        hi_intelligence_event_time,
        is_hi_intelligence,
        hi_qa_msg_from,
        hi_qa_msg_send_name,
        hi_qa_msg_id,
        hi_qa_msg_type,
        hi_qa_k8s_svc_name,
        hi_qa_k8s_env_name,
        hi_qa_event_time,
        is_hi_qa,
        conversation_start_time,
        conversation_end_time,
        cmd_k8s_env_name,
        dt
    from dim_audio_process;