-- cdmods.ods_cloud_db_c0007_asset_asset_s_d cloud asset_asset 主机资产表
create external table cdmods.ods_cloud_db_c0007_asset_asset_s_d(
  id int comment 'id',
  ip string comment 'ip 地址',
  hostname string comment 'hostname 地址',
  platform string comment '操作平台',
  is_active int comment '是否在线，1:在线,0:不在线',
  public_ip string comment '公网ip地址',
  vendor string comment '设备供应商',
  model string comment '设备型号',
  sn string comment '产品序列号',
  cpu_model string comment 'CPU型号',
  cpu_count int comment 'CPU个数',
  cpu_cores int comment 'CPU核心数',
  cpu_vcpus int comment 'CPU虚拟核心数',
  memory string comment '内存大小',
  disk_total string comment '磁盘大小',
  disk_info string comment '磁盘信息',
  os string comment '操作系统',
  os_version string comment '操作系统版本',
  os_arch string comment '操作系统架构',
  created_by string comment '创建者',
  date_created string comment '创建时间',
  comment string comment '备注',
  group_id int comment '组id',
  idc string comment '托管服务商',
  usage string comment '用途',
  cabinet_id int comment '机架号',
  ipmi_ip string comment 'ipmi ip',
  service_ip string comment '服务ip',
  gpu_count int comment 'GPU个数',
  gpu_model string comment 'GPU型号',
  host_type string comment '主机组',
  kernel string comment '内核版本',
  cpu_load string comment 'cpu负载',
  ldap_status int comment 'ldap是否接入状态 1:接入,0:未接入',
  mem_free string comment '剩余内存',
  extension string comment '扩展字段',
  hosting_type string comment '主机类型',
  k8s_env_name string comment '环境名称'
)
comment 'cloud ods_cloud_db_c0007_asset_asset_s_d 主机资产表'
PARTITIONED BY (dt string COMMENT '日期')
STORED AS parquet;