create external table cdmods.ods_crio_db_c0028_partrollog_i_d (
     projectCode string comment '项目code',
     `level` string comment '备注-无意义',
     pubtime bigint comment '记录入库时间',
     id string comment 'mongo ID',
     `describe` string comment '任务描述,当前状态执行状态的一个描述',
     robotid string comment 'robot id',
     type string comment '备注-无意义',
     projectName string comment '项目名称',
     title string comment '巡逻事件类型,巡逻事件告警id',
     tenant string comment '租户',
     taskName string comment '任务名称',
     startTime string comment '开始时间',
     stopTime string comment '停止时间',
     pauseTime string comment '暂停时间',
     resumeTime string comment '恢复时间',
     planEndTime string comment '计划结束时间',
     finishTime string comment '完成时间',
     finishTimes int comment '完成次数',
     runningTime int comment '运行次数',
     locationLostTime string comment '位置丢失时间',
     avoidanceTime string comment '避障时间',
     avoidanceTimes int comment '避障次数',
     checkInTimes int comment '检查次数',
     ttsPlayTimes int comment '本次任务语音播报次数',
     planRepeatTimes int comment '本次任务计划圈数',
     planPointTasks int comment '本次任务计划巡更点数量',
     finishPointTasks int comment '本次任务完成巡更点数量',
     battery int comment '当前电量',
     averageBattery double comment '本次任务平均每圈耗电',
     mileage double comment '本次任务完成里程，单位米',
     averageMileage double comment '本次任务平均每圈里程',
     x int comment '当前点位',
     y int comment '当前点位',
     uuid string comment '当前状态唯一的uuid,state_id 即研发的taskid',
     jobid string comment '工作id',
     companyCode string comment '公司代码',
     companyName string comment '公司名称',
     k8s_env_name string comment '环境名称'
)
comment 'mongo dams.patrollog 机器人巡逻日志记录'
PARTITIONED BY (dt string COMMENT '日期')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.JsonSerDe'
STORED AS TEXTFILE;