create external table cdmods.ods_thd_gx_clean_robot_detail_i_d(
	robotProductID string comment '',
    gsRobotTaskQueueEndTimeStr string comment '',
    gsRobotTaskQueueDuration string comment '',
    gsRobotTaskQueueID string comment '',
    gsRobotTaskQueueMapUUID string comment '',
    gsRobotTaskQueueDeviceStatus string comment '',
    gsRobotTaskQueueWaterUsageCalc string comment '',
    gsRobotTaskQueueTaskQueueID string comment '',
    robotSuctionBladeReliability string comment '',
    robotFilterReliability string comment '',
    gsRobotTaskQueuePathName string comment '',
    gsRobotTaskQueueSoftwareVersion string comment '',
    gsRobotTaskQueueWaterUsage string comment '用水量',
    gsRobotTaskQueueCleaningMode string comment '',
    gsRobotTaskQueueCompleteness string comment '任务完成比',
    gsRobotTaskQueueMapName string comment '地图名称',
    gsRobotTaskQueueProtocol string comment '',
    gsRobotTaskQueueEndBatteryLevel string comment '',
    gsRobotTaskQueueUseTime string comment '工作时长',
    gsRobotTaskQueueOperator string comment '操作员',
    gsRobotTaskQueueRealProductivity string comment '',
    gsRobotTaskQueuePreSuctionBladeUsage string comment '',
    gsRobotTaskQueueCoverageArea string comment '清洁区域',
    gsRobotTaskQueueBrushUsage string comment '刷盘',
    gsRobotTaskQueueProductID string comment 'S/N robotId',
    gsRobotTaskQueueFilterUsage string comment '滤芯',
    gsRobotTaskQueueRobotAlias string comment '机器名',
    gsRobotTaskQueueEndTime string comment '结束时间',
    gsRobotTaskQueueExpectedProductivity string comment '',
    gsRobotTaskQueueStartTime string comment '开始时间',
    robotBruashReliability string comment '',
    gsRobotTaskQueueBrushUsageAlert string comment '',
    gsRobotTaskQueueSuctionBladeUsageAlert string comment '',
    gsRobotTaskQueueStartTimeStr string comment '',
    gsRobotTaskQueueTaskName string comment '任务名称',
    gsRobotTaskQueueFilterUsageAlert string comment '',
    gsRobotTaskQueueTaskWorkStatus string comment '',
    robotModelTypeCode string comment '',
    gsRobotTaskQueueTaskImageName string comment '',
    robotRobotFamilyCode string comment '',
    gsRobotTaskQueueSuctionBladeUsage string comment '吸水条',
    gsRobotTaskQueueBeginBatteryLevel string comment '',
    `date` string comment '日期'
)PARTITIONED BY (dt string comment '日期')
ROW FORMAT
SERDE 'org.apache.hadoop.hive.serde2.JsonSerDe'STORED AS TEXTFILE
location '/data/cdmods/ods_thd_gx_clean_robot_detail_i_d';