-- cdmdwm.dwm_svo_qa_op_i_d qa_op operator每次qa操作记录,每个qa的绩效统计
create external table cdmdwm.dwm_svo_qa_op_i_d (
    event_id string comment 'ID',
    qa_id string comment 'qa的id',
    qa_type string comment 'qa类型,fqa user_qa',
    operator_id string comment '操作者id',
    operator string comment '操作者',
    operation string comment '操作动作',
    agent_id string comment 'agent id,只有user_qa才有',
    question_added string comment '增加的问题',
    question_add_num int comment '增加的问题数量',
    answer_added string comment '增加的回答',
    answer_add_num int comment '增加的回答数量',
    qa_id_old string comment '旧的qa id',
    qa_cate_id_old string comment '旧的fqa类别id',
    qa_cate_name_old string comment '旧的fqa类别名称',
    status_old int comment '老的状态值：0没有生效 1生效',
    status_name_old string comment '老的状态值：0没有生效 1生效',
    emoji_old string comment '旧的emoji表情',
    tags_old string comment '旧的标签',
    pid_old string comment '旧的cate父id',
    level_old int comment '旧的cate level',
    is_work_old int comment '旧的cate是否生效 0:no 1:yes',
    is_work_name_old string comment '旧的cate是否生效 0:no 1:yes',
    cate_id_path_old string comment '旧的cate分类id path',
    cate_name_path_old string comment '分类cate name path',
    audit_name_old string comment '旧的cate记录操作轨迹',
    question_sim_old string comment '旧的相似问题组',
    question_length_old int comment '旧的相似问题数量',
    answer_sim_old string comment '旧的相似回答组',
    answer_length_old int comment '旧的相似回答数量',
    qa_id_new string comment '新的qa id',
    qa_cate_id_new string comment '新的fqa类别id',
    qa_cate_name_new string comment '新的fqa类别名称',
    status_new int comment '新的状态值：0没有生效 1生效',
    status_name_new string comment '新的状态值：0没有生效 1生效',
    emoji_new string comment '新的emoji表情',
    tags_new string comment '新的标签',
    pid_new string comment '新的cate父id',
    level_new int comment '新的cate level',
    is_work_new int comment '新的cate 是否生效 0:no 1:yes',
    is_work_name_new string comment '是否生效 0:no 1:yes',
    cate_id_path_new string comment '新的cate 分类id path',
    cate_name_path_new string comment '分类cate name path',
    audit_name_new string comment '新的cate记录操作轨迹',
    question_sim_new string comment '新的相似问题组',
    question_length_new int comment '旧的相似问题数量',
    answer_sim_new string comment '新的相似回答组',
    answer_length_new int comment '旧的相似回答数量',
    work_cnt int comment '当前qa的work数,即操作者的任务数,取数逻辑为新的与旧的question&answer的差的绝对值，如果相等取1否则为两差值之和',
    file_path string comment '文件路径',
    memo string comment '备忘录',
    language string comment '语言',
    k8s_env_name string comment '数据来源环境',
    event_time string comment '操作时间'
)
comment 'qa_op operator每次qa操作记录,每个qa的绩效统计'
partitioned by(dt string comment 'dt分区字段')
stored as parquet
location '/data/cdmdwm/dwm_svo_qa_op_i_d';