CREATE EXTERNAL TABLE cdmods.ods_crio_db_c0010_t_task_i_d(
     id bigint comment "任务ID",
     uuid string comment "任务计划uuid",
     name string comment "名称",
     code string comment "编码",
     tenant_id bigint comment "租户id",
     tenant_name string comment "租户名称",
     tenant_code string comment "租户编码",
     device_id bigint comment "设备id",
     robot_type string comment "机器人类型",
     robot_name string comment "机器人名称",
     robot_model string comment "机器人型号",
     robot_code string comment "机器人编码",
     map_id bigint comment "所属地图ID",
     map_name string comment "地图名称",
     map_code string comment "地图编码",
     task_type int comment "任务类型 0: 临时任务 1：定时任务",
     work_types string comment "工作类型 0:洗地 1:吸污 2:扫地3:广告4:尘推",
     repeat_times int comment "重复次数，0表示无数次",
     days string comment "星期几（启动日期）",
     start_time string comment "任务开始时间",
     end_time string comment "任务结束时间",
     repeat_type int comment "循环周期，日循环：1，周循环：7，月循环：30",
     sub_tasks string comment "子任务,json数组",
     create_time string comment "创建时间",
     update_time string comment "修改时间",
     version int comment "乐观锁版本号",
     biz_task_type int comment "业务任务类型 0.送货任务，1.引领任务，2.闹钟任务，10.寄件任务，11.派件任务，20.消杀任务",
     biz_task_type_name string comment "业务任务类型名称 0.送货任务，1.引领任务，2.闹钟任务，10.寄件任务，11.派件任务，20.消杀任务",
     point_info string comment "消杀任务兴趣点信息",
     duration int comment "消杀任务消杀时间，单位分钟，默认5分钟，最大120分钟",
     guide_tour string comment "导览任务",
     create_by string comment "任务计划创建人",
     update_by string comment "任务计划修改人",
     route_id  bigint comment "路线ID",
     event_time BIGINT comment '事件发生时间',
     bigdata_method string comment 'db操作类型:INSERT;UPDATE;DELETE',
     k8s_env_name string  comment '环境名称'
) COMMENT '清洁-crss_task-t_task'
PARTITIONED BY (dt string COMMENT '日期')
STORED AS parquet
location '/data/cdmods/ods_crio_db_c0010_t_task_i_d/';