create external table cdmods.ods_crio_db_c0010_t_task_log_i_d(
     id bigint  comment '任务日志ID',
     parent_id bigint  comment '父任务日志ID',
     task_id bigint  comment '任务ID,仅供参考，因为任务数据会被删掉',
     uuid string comment '任务uuid,随上报的任务状态变更时带上来的',
     task_uuid string comment '任务uuid',
     tenant_id bigint comment '租户ID',
     tenant_name string comment '租户名称',
     tenant_code string comment '租户编码',
     device_id bigint comment '所属机器人ID',
     device_type int comment '所属机器人类型id值,3：ginger-lite',
     robot_status int comment '状态 1：有效 9：删除',
     robot_type string comment '所属机器人类型名称',
     robot_code string comment '所属机器人编码',
     robot_name string comment '所属机器人名称',
     rcu_code string comment 'rcu编码',
     rcu_name string comment 'rcu名称',
     map_code string comment '所属地图编码',
     map_name string comment '所属地图名称',
     map_route_id string comment '地图路径ID',
     map_route_name string comment '地图路径名称',
     task_type int comment '所属任务类型,0:送货 1:引领 2:闹钟 10:快递通寄件 11:快递通派件 12:消杀 13:导览',
     work_types string comment '所属工作类型',
     task_code string comment '所属任务编码',
     task_name string comment '所属任务名称',
     area_finish string comment '完成清洁面积(m2)',
     area_plan string comment '计划清洁面接(m2)',
     water string comment '消耗的水量(L)',
     distance string comment '行驶距离(m)',
     `percent` string comment '覆盖率百分比',
     battery string comment '消耗电量百分比',
     efficiency string comment '清洁效率(m2/h)',
     speed string comment '平均速率(m/s)',
     schedule_time string comment '任务计划执行时间',
     start_time string comment '任务开始时间字符串',
     start_timestamp bigint comment '任务开始的时间戳',
     start_time_utc string comment '任务开始的UTC时间',
     end_time string comment '任务结束时间字符串',
     end_timestamp bigint comment '任务结束的时间戳',
     end_time_utc string comment '任务结束的UTC时间',
     status int comment '任务状态,-1:未执行 0：发起失败 1：进行中 2：异常挂起 3：异常结束 4：成功结束 5：取消结束',
     `action` int comment '兴趣点行为,可为null',
     task_mode int comment '0:机器人发起 1:CROSS发起 2:语音发起',
     version int comment '乐观锁版本号',
     create_time string comment '创建时间',
     update_time string comment '更新时间',
     `year` int comment '年',
     `month` int comment '月',
     `day` int comment '日',
     record_state int comment '录制状态,0:启动成功 1：启动录制失败 2：停止录制成功 3:停止录制失败 9:不需要录制',
     work_data string comment '工作数据',
     error_code string comment '错误码',
     error_message string comment '错误信息',
     error_detail string comment '错误详情',
     biz_type int comment '业务类型: 0-智能服务机器人 1-快递通系统',
     task_point_sum int comment '任务执行兴趣点总数',
     branch_id int comment '分支机构ID',
     branch_tag string comment '分支机构链',
     operating_status int comment '运营状态 1 空闲 2 测试中 3 演示中 4 运营中 5 交付中 6待回收',
     running_status int comment '运行状态 1 正常 2 停用 3 故障 4 维修中',
     event_flag int comment '事件生成类型 0=未生成 1=任务未执行 2=任务更新超时',
     source string comment '来源：H5, CROSS, HARIX, HA, VOICE',
     bigdata_method string comment 'db操作类型:INSERT;UPDATE;DELETE',
     k8s_env_name string  comment '环境名称'
)
comment 'jinger任务日志crss_task.t_task_log'
PARTITIONED BY (dt string COMMENT '日期')
STORED AS parquet
location '/data/cdmods/ods_crio_db_c0010_t_task_log_i_d';