-- cdmods.ods_crio_db_c0012_vending_i_d 货柜信息
create external table cdmods.ods_crio_db_c0012_vending_i_d(
     id bigint comment '货柜id',
     tenant_id bigint comment '租户ID',
     tenant_code string comment '租户编码',
     branch_id bigint comment '分支机构ID',
     region_id bigint comment '省市区',
     name string comment '设备名称',
     service_code string comment '服务编码',
     rcu_code string comment 'RCU号',
     robot_type string comment 'Robot类型',
     robot_code string comment 'Robot号',
     roc_user_code string comment 'ROC user code',
     online_flag string comment '在线标识\r\n0：离线\r\n1：在线',
     hari_service_flag string comment '服务标识\r\n0：未连接\r\n1：AI服务中\r\n2：人工服务中\r\n3：服务中断',
     longitude string comment '经度',
     latitude string comment '纬度',
     status bigint comment '状态\r\n1：有效\r\n9：删除',
     model string comment '货柜型号',
     location string comment '地址',
     scene string comment '使用场景',
     door_status bigint comment '门状态\r\n0：关\r\n1：开',
     lock_status bigint comment '锁状态\r\n0：关\r\n1：开',
     door2_status bigint comment '门状态 0：关 1：开',
     lock2_status bigint comment '锁状态 0：关 1：开',
     firmware_version string comment '固件版本',
     software_version string comment '软件版本',
     deliver_person_id bigint comment '配货人员',
     stockin_person_id bigint comment '上货人员',
     create_time string comment '创建时间',
     update_time string comment '修改时间',
     version bigint comment '乐观锁版本控制',
     layout_id bigint comment '摆放规则id',
     floor_sku string comment '层级库存',
     shfp_flag bigint comment '社会扶贫专柜标识：0-未注册，1-已注册，2-已激活',
     door_post_url string comment '门贴URL',
     shfp_machine_sn string comment '扶贫网机柜编号',
     signal_value string comment '信号强度',
     gen_order_way int comment '货柜生成订单的方式 1-美智 0-自研',
     dl_status_flag int comment '门锁状态标识 0-异常 1-正常',
     temperature string comment '货柜实时温度',
     tmp_param string comment '货柜温度控制策略',
     volume int comment '音量',
     address_type_code int comment '场所类别编码，如：学校、购物商场、商务办公场所等',
     scenes_id bigint comment '场景id',
     repository_id bigint comment '库位id',
     sku string comment '货柜sku',
     sim_card string comment '货柜使用的sim卡号'
)
comment '货柜信息crss_cvms.vending'
PARTITIONED BY (dt string COMMENT '日期')
STORED AS parquet;