#clickhouse连接地址
#clickhouse_url: jdbc:clickhouse://clickhouse.cloudminds.com:9090/ceph_meta
#clickhouse_url: jdbc:clickhouse://172.16.32.96:9090/ceph_meta
#clickhouse_username: distributed-write
#clickhouse_password: CloudMinds#
#clickhouse_tablename: ceph_meta.dwd_ceph_nginx_log
clickhouse_url: jdbc:clickhouse://10.11.33.163:8125/ceph_meta
clickhouse_username: chengkang
clickhouse_password: chengkang123
clickhouse_tablename: ceph_meta.dwd_roc_report_metrics_new

#checkpoint存储位置
fs_stateBackend: hdfs://nameservice1/tmp/reportMetrics/${now}