create external table cdmdwm.dwm_svo_asr_label_event_i_d(
    event_type_id string comment '事件编码的值',
    event_name string comment '事件名称',
    event_time string comment '事件时间,精确到毫秒(北京时间)',
    model_id string comment '模块id',
    option string comment '扩展字段',
    operator_id string comment '标注人ID',
    project_id string comment '项目ID',
    label_type_id string comment '标签类型ID 1.音频可用 2. 音频不可用 3. 音频备用',
    -- label_type_name string comment '标签类型描述',
    label_id string comment '标签ID',
    label_name string comment '标签名',
    question_id string comment '端到端对话 的chuanID',
    asr_correct_text string comment 'asr修正内容',
    audio_correct_text string comment '粗标修正内容',

    sv_agent_id string comment 'smart voice 的agent id',
    sv_agent_name string comment 'smart voice 的agent名称',
    question_text string comment '识别的文本,识别得文本为空也不会请求nlp',
    answer_text string comment 'nlu处理识别的文本后返回的意图文本',
    sv_answer_text string comment 'nlu处理识别的文本后返回的意图文本',
    qa_from string comment '提供qa服务的模块',
    nlu_event_time string comment 'nlu事件发生时时间',
    submit_time string comment '标注批次任务提交时间',

    -- 租户
    tenant__tenant_id string comment '租户id',
    tenant__tenant_name string comment '租户名称',
    tenant__tenant_type string comment '租户类型',
    tenant__industry_id string comment '租户所属行业id',
    tenant__industry_name string comment '租户所属行业id',
    tenant__sub_sys string comment '子系统',
    tenant__time_zone string comment '时区',
    tenant__net_env_id string comment '网络环境',
    tenant__mcs_area string comment 'mcs区域',
    tenant__device_num int comment '最大设备数',
    tenant__region string comment '地区',
    tenant__address string comment '地址',
    tenant__contact string comment '租户联系人',
    tenant__phone string comment '联系电话',
    tenant__telephone string comment '联系电话',
    tenant__seller string comment '销售人员',
    tenant__email string comment '邮箱地址',
    tenant__status int comment '租户状态: -1-删除;0-正常;1-待开通;2-锁定',
    tenant__status_name string comment '租户状态',
    tenant__charge_time string comment '计费开始时间',
    tenant__expired_time string comment '租户过期时间',
    tenant__logo string comment '租户logo地址',
    tenant__description string comment '租户简要描述',
    tenant__brand string comment '客户品牌化参数',
    tenant__is_need_vpn int comment '是否需要VPN: 0-不需要,1-需要',
    tenant__create_time string comment '租户创建时间',


     -- robot
    robot__robot_id string comment '机器人id标识，既是robot_code',
    robot__robot_name string comment '机器人名称',
    robot__robot_type_id string comment '机器人类型',
    robot__robot_type_inner_name string comment '机器人类型名(研发)',
    robot__robot_type_name string comment '机器人类型名',
    robot__asset_code string comment '资产code',
    robot__asset_type string comment '资产类型',
    robot__product_type_code string comment '产品类型code',
    robot__product_type_code_name string comment '产品类型code所对应的名称',
    robot__product_id string comment '产品ID',
    robot__product_id_name string comment '产品名字',
    robot__assets_status int comment '资产状态 0-在册 1-在库 2-出库',
    robot__assets_status_name string comment '资产状态 在册 在库 出库',
    robot__status int comment '机器人状态 robot状态: -1-删除 0-正常 1-停用',
    robot__status_name string comment '机器人状态',
    robot__robot_manufacturer_id string comment '机器人制造商id',
    robot__robot_manufacturer_name string comment '机器人制造商名称',
    robot__model string comment 'robot型号,roc中model boss中device_model',
    robot__os string comment '操作系统平台',
    robot__version_code string comment '版本号',
    robot__software_version string comment '机器人软件版本',
    robot__hardware_version string comment '机器人硬件版本',
    robot__head_url string comment '展示头像',
    robot__regist_time string comment '注册时间',
    robot__bind_status int comment '机器人受控状态: -1-删除 0-注册未激活 1-激活可用 2-通知VPN注册',
    robot__bind_status_name string comment '机器人受控状态名',
    robot__is_hi_service int comment '人工服务: 0-禁止，1-允许',
    robot__is_privacy_enhance int comment '隐私增强：0-关闭，1-开启',
    robot__remind_policy_id string comment '提醒策略id',
    robot__sku string comment '机器人SKU',
    robot__quality_date string comment '供应商质保期',
    robot__customer_quality_date string comment '客户质保期',
    robot__out_type_state int comment '出库类型 0 交付出库 1 维修出库 2 报废出库 3 交付给客户 4 交付给测试',
    robot__out_type_state_name string comment '出库类型 0 交付出库 1 维修出库 2 报废出库 3 交付给客户 4 交付给测试',
    robot__product_date string comment '生产日期',
    robot__in_stock_date string comment '入库日期',
    robot__out_stock_date string comment '出库日期',
    robot__in_stock_staff_id string comment '入库操作人员ID',
    robot__in_stock_staff_name string comment '入库操作人员姓名',
    robot__out_stock_staff_id string comment '出库操作人员ID',
    robot__out_stock_staff_name string comment '出库操作人员姓名',
    robot__robot_note string comment '备注',
    robot__description string comment '机器人信息描述',
    robot__create_time string comment '机器人创建时间',


     -- robot_account_id
    robot_account__robot_account_id string comment '机器人账户，roc系统中创建的机器人账号',
    robot_account__robot_account_name string comment '姓名',
    robot_account__email string comment '邮件地址',
    robot_account__phone string comment '手机号码',
    robot_account__status int comment '有效生命周期内用户状态,即机器人账户: -1-删除,0-正常,1-停用',
    robot_account__status_name string comment '有效生命周期内用户状态,即机器人账户: -1-删除,0-正常,1-停用',
    robot_account__privacy_type int comment '隐私类型: 1-公共, 2-私有',
    robot_account__privacy_type_name string comment '隐私类型: 1-公共, 2-私有',
    robot_account__is_hi_service int comment '人工服务: 0-禁止，1-允许',
    robot_account__is_privacy_enhance int comment '隐私增强：0-关闭，1-开启',
    robot_account__is_auto_takeover int comment '允许自动接管: 0-禁止，1-允许',
    robot_account__app_id string comment 'app应用id',
    robot_account__video_mode string comment '视频模式：videocall, videoroom',
    robot_account__phone_number_prefix string comment '手机号码前缀',
    robot_account__operator_id string comment 'roc操作人员id',
    robot_account__ross_credential_id string comment 'idoe中的ross-credential-id',
    robot_account__create_time string comment '机器人账户创建时间',

    -- 2021-11-05新增需求补充字段
    fqa_cate__cate_name_path string comment '分类cate name path',
    user_qa_cate__cate_name_path string comment '分类cate name path',
    rcu_audio string comment '机器人录制的RCU声音文件',
    is_noise int comment '是否是噪音 1-表示噪音，0-表示不是噪音',
    qa_flag string comment 'qa问题来源,HI CLOUD',
    asr_vendor string comment 'asr提供商',
    dialect string comment '本地方言',
    algo string comment '算法类型',
    hi_intelligence_msg string comment '数据内容,对应日志中eventContent,hi 事件中的消息',
    hi_intelligence_msg_from string comment '数据内容来源，hiChatListConfirmSimQ-确认问题 答案中的相似问题,hiChatListConfirmGW-确认问题  GW 中的问题,hiChatListConfirmAiAnswer-确认答案 有无信心都可点击,hiQuestionPanel - 输入框输入的问题,hiAnswerPanel - 输入框输入的答案,hiDancePanel - 常用舞蹈  对应上面isAction 为true,hiActionPanel - 常用动作  对应上面isAction 为true,hiShortcutPanel - 自定义面板中  自定义按钮，包括问题和答案,hiPhaseList - 常用短语',
    hi_intelligence_msg_from_name string comment '数据内容来源，hiChatListConfirmSimQ-确认相似问题,hiChatListConfirmGW-确认问题gateway问题,hiChatListConfirmAiAnswer-确认答案 ,hiQuestionPanel - 输入框输入问题,hiAnswerPanel - 输入框输入答案,hiDancePanel - 常用舞蹈  对应上面isAction 为true,hiActionPanel - 常用动作  对应上面isAction 为true,hiShortcutPanel - 自定义按钮，包括问题和答案,hiPhaseList - 常用短语',
    hi_intelligence_msg_type string comment 'question、answer、action',
    is_hi_intelligence int comment '是否坐席增强, 1-坐席增强 0-坐席未增强',

        -- 坐席发送qa
    hi_qa_msg_from string comment '消息发出的模块',
    hi_qa_msg_send_name string comment '消息发出的用户名',
    is_hi_qa int comment '坐席是否发送qa, 1-坐席发送qa 2-坐席未发送qa',
    question_language string comment '识别的文本,语言类型',
    cmd_k8s_env_name string comment '会话环境信息,如果环境为221,join时候使用232join',
    nlu_k8s_env_name string comment 'k8s环境名称',
    intent__intent_id string comment 'intent id',
    intent__intent_name string comment 'intent 名称',
    domain__domain_id string comment 'domain id',
    domain__domain_name string COMMENT 'domain 名称',
    asr_domain string comment 'asr domain'
)
comment 'asr标注事件日志宽表'
partitioned by (dt string comment '分区日期')
stored as parquet;