-- cdmods.ods_crio_db_c0001_tenant_a_d boss系统租户表crss_upms.tenant
CREATE EXTERNAL TABLE cdmods.ods_crio_db_c0001_tenant_s_d(
    id int comment 'ID',
    vop_id int COMMENT '关联的虚拟运营商id',
    name string COMMENT '租户名称',
    code string COMMENT '租户code',
    phone_area_code string COMMENT '手机区域编码',
    phone string COMMENT '手机号码',
    status string COMMENT '状态：有效：删除',
    create_time timestamp COMMENT '创建时间',
    update_time timestamp COMMENT '修改时间',
    version int COMMENT '乐观锁版本号',
    service_address string COMMENT '服务地址',
    contacts string COMMENT '联系人',
    type string COMMENT '1长租、2短租、3售卖、4试用、5测试',
    industry string COMMENT '行业',
    project_name string COMMENT '项目名称',
    district string COMMENT '所属地图',
    description string COMMENT '描述信息',
    email string COMMENT '邮箱',
    phone_code string COMMENT '手机号',
    log string COMMENT 'log',
    environment string COMMENT '属于哪个环境  test231  prod231',
    sub_business string COMMENT '子业务列表',
    time_zone string COMMENT '时区',
    time_zone_name string COMMENT '时区名称',
    update_timestamp bigint COMMENT '更新名称',
    country string COMMENT '国家',
    province string COMMENT '省份',
    city string COMMENT '城市',
    address string COMMENT '地址',
    customer_id int COMMENT '客户id',
    salesman string COMMENT '销售人员',
    vpn_user_limit int COMMENT '最大设备数',
    vpn_zone_codes string COMMENT '区域编码',
    mail  string COMMENT '邮箱地址',
    k8s_env_name string COMMENT '环境名称'
)COMMENT 'boss系统字典表crss_upms.tenant 租户相关信息'
PARTITIONED BY (dt string COMMENT '日期')
STORED AS parquet;