CREATE EXTERNAL TABLE cdmods.ods_roc_db_c0008_t_tenant_s_d(
	tenant_code string COMMENT '租户编码',
	tenant_name string COMMENT '租户名称',
	address string COMMENT '租户地址',
	contacts string COMMENT '联系人',
	phone_code string COMMENT '租户手机号码',
	telephone string COMMENT '租户联系电话',
	email string COMMENT '租户电子邮箱',
	create_time string COMMENT '租户创建时间',
	update_time string COMMENT '租户更新时间',
	status int COMMENT '租户状态: -1-删除;0-正常;1-待开通;2-锁定',
	charge_time string COMMENT '计费开始时间',
	expired_time string COMMENT '租户过期时间',
	logo string COMMENT '租户logo地址',
	tenant_type int COMMENT '客户类型: 0-长租;1-短租;2-试用',
	hari_address string COMMENT 'hari服务访问地址',
	hari_port bigint COMMENT 'hari服务访问端口',
	description string COMMENT '租户简要描述',
	vpn_user_limit bigint COMMENT 'VPN限制用户数量',
	vpn_user_num bigint COMMENT 'vpn当前用户数量',
	branding string COMMENT '客户品牌化参数',
	ice_locator string COMMENT 'IceGrid注册节点的位置',
	ice_endpoints string COMMENT 'IceGrid端点',
	project_name string COMMENT '项目名称',
	region string COMMENT '所属地区',
	deliverer string COMMENT '交付人员',
	delivery_time string COMMENT '交付时间',
    remind_policy_id string COMMENT '提醒策略ID',
    industry int COMMENT '行业: 1-其它，2-银行; 3-医疗服务; 4-房地产; 5-互联网; 6-通信',
	need_vpn int COMMENT '是否需要VPN: 0-不需要;1-需要',
	rcu_recording string COMMENT 'RCU视频录制配置',
	camera_recording string COMMENT '摄像头录制配置',
	open_time string COMMENT '计费开始时间',
	phone_number_prefix string COMMENT '手机号码前缀',
	k8s_env_name string COMMENT '环境名称'
	)COMMENT 'roc prod表roc.t_tenant 租户相关信息'
PARTITIONED BY ( dt string COMMENT '日期')
STORED AS parquet;