CREATE EXTERNAL TABLE cdmods.ods_roc_db_c0008_t_rcu_s_d(
  id string COMMENT '信息ID', 
  tenant_code string COMMENT '隶属租户code', 
  rcu_code string COMMENT 'RCU唯一标识rcuId值', 
  imei string COMMENT 'imei号', 
  rcu_name string COMMENT 'RCU名称', 
  manufacturer string COMMENT 'RCU厂商', 
  model string COMMENT 'RCU型号,例如: A1-901', 
  os string COMMENT '操作系统平台', 
  version_code string COMMENT ' 版本号', 
  cpu string COMMENT 'cpu信息', 
  ram string COMMENT 'ram信息', 
  rom_capacity string COMMENT 'rom总容量', 
  rom_available_capacity string COMMENT 'rom可用空间', 
  sd_capacity string COMMENT 'sd卡容量', 
  sd_available_capacity string COMMENT 'sd卡可用空间', 
  camera string COMMENT '摄像头', 
  wifi_mac string COMMENT 'wifi mac地址', 
  bluetooth_mac string COMMENT '蓝牙mac地址', 
  power_status string COMMENT '电源状态', 
  boot_time bigint COMMENT '开机时长', 
  last_online_time string COMMENT '最后在线时间', 
  online_flag int COMMENT 'RCU是否在线: 0-不在线\; 1-在线', 
  status int COMMENT 'RCU状态: -1-删除\;0-正常\;1-停用', 
  regist_time string COMMENT '注册时间', 
  activate_time string COMMENT '激活时间', 
  description string COMMENT '描述信息', 
  update_time string COMMENT 'RCU信息更新时间', 
  did string COMMENT 'Decentralized Identifier', 
  deactivate_time string COMMENT '取消激活时间', 
  did_credential_id string COMMENT 'idoe中的did-credential-id',
  k8s_env_name string COMMENT '环境名'
)
PARTITIONED BY (dt string) 
-- row format delimited fields terminated by '\001'  
STORED AS PARQUET ;